package frc.robot.constants;

import frc.powerlib.tuning.TunableConstants;

/** Regenerated by Update Code to register constants for the current subsystems. */
public final class GeneratedTunableConstants {
  private GeneratedTunableConstants() {}

  public static void register() {
    TunableConstants.register(VisionConstants.class);
    TunableConstants.register(StateMachineConstants.class);
    TunableConstants.register(OIConstants.class);
    TunableConstants.register(RobotContainerConstants.class);
    TunableConstants.register(SwerveConstants.class);
  }
}
