param(
    [switch]$SkipBuild,
    [switch]$UpdateSubsystems,
    [switch]$UpdateBindings,
    [string]$SubsystemsJson = "powerlib-subsystems.json",
    [string]$BindingsJson = "powerlib-bindings.json"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$StateMachineStartMarker = "  // POWERLIB GENERATED SUBSYSTEMS START - DO NOT DELETE"
$StateMachineEndMarker = "  // POWERLIB GENERATED SUBSYSTEMS END - DO NOT DELETE"
$ConstantsStartMarker = "  // POWERLIB GENERATED CONSTANTS START - DO NOT DELETE"
$ConstantsEndMarker = "  // POWERLIB GENERATED CONSTANTS END - DO NOT DELETE"
$BindingConstantsStartMarker = "  // POWERLIB GENERATED BINDING CONSTANTS START - DO NOT DELETE"
$BindingConstantsEndMarker = "  // POWERLIB GENERATED BINDING CONSTANTS END - DO NOT DELETE"
$CharacterizationStartMarker = "    // POWERLIB GENERATED CHARACTERIZATION START - DO NOT DELETE"
$CharacterizationEndMarker = "    // POWERLIB GENERATED CHARACTERIZATION END - DO NOT DELETE"
$GeneratedFileMarker = "// Generated by PowerLib subsystem tool. Edit powerlib-subsystems.json, then run update."
$SubsystemIdMarkerPrefix = "// POWERLIB SUBSYSTEM ID: "
$CustomConstantsStartMarker = "  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE"
$CustomConstantsEndMarker = "  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE"
$BuiltInConstantNames = @("CanBus", "LED", "Location", "OI", "Tuner", "Vision")

function Prompt-Value {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    $suffix = ""
    if ($null -ne $DefaultValue -and $DefaultValue.Length -gt 0) {
        $suffix = " [$DefaultValue]"
    }

    [Console]::WriteLine()
    [Console]::Write("POWERLIB> $Message$suffix`: ")
    $value = [Console]::ReadLine()
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $DefaultValue
    }

    return $value.Trim()
}

function Prompt-Required {
    param([Parameter(Mandatory = $true)][string]$Message)

    do {
        $value = Prompt-Value $Message
    } while ([string]::IsNullOrWhiteSpace($value))

    return $value.Trim()
}

function Prompt-Enum {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Parameter(Mandatory = $true)][string[]]$AcceptedValues,
        [Parameter(Mandatory = $true)][string]$DefaultValue
    )

    $acceptedText = $AcceptedValues -join ", "
    while ($true) {
        $value = Prompt-Value "$Message (accepted: $acceptedText)" $DefaultValue
        foreach ($accepted in $AcceptedValues) {
            if ($value -ieq $accepted) {
                return $accepted
            }
        }

        Write-Host "Accepted values: $acceptedText"
    }
}

function Prompt-Boolean {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [bool]$DefaultValue = $false
    )

    $defaultText = if ($DefaultValue) { "y" } else { "n" }
    while ($true) {
        $value = (Prompt-Value "$Message (accepted: y, n)" $defaultText).ToLowerInvariant()
        if ($value -eq "y" -or $value -eq "yes" -or $value -eq "true") {
            return $true
        }
        if ($value -eq "n" -or $value -eq "no" -or $value -eq "false") {
            return $false
        }

        Write-Host "Accepted values: y, n"
    }
}

function Prompt-Int {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Nullable[int]]$DefaultValue = $null
    )

    while ($true) {
        $defaultText = if ($null -eq $DefaultValue) { $null } else { $DefaultValue.ToString() }
        $value = Prompt-Value $Message $defaultText
        $parsed = 0
        if ([int]::TryParse($value, [ref]$parsed)) {
            return $parsed
        }

        Write-Host "Please enter a whole number."
    }
}

function Prompt-DoubleText {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    while ($true) {
        $value = Prompt-Value $Message $DefaultValue
        $parsed = 0.0
        if ([double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
            return $value
        }

        Write-Host "Please enter a number."
    }
}

function Prompt-OptionalDoubleText {
    param([Parameter(Mandatory = $true)][string]$Label)

    $value = Prompt-Value "$Label (blank for Optional.empty)" ""
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $null
    }

    $parsed = 0.0
    if (-not [double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        throw "Please enter a number for $Label."
    }

    return $value
}

function Get-JavaIdentifierParts {
    param([Parameter(Mandatory = $true)][string]$Value)

    $splitWords = [regex]::Replace($Value, "([a-z])([A-Z])", '$1 $2')
    return @($splitWords -split "[^A-Za-z0-9]+" | Where-Object { $_.Length -gt 0 })
}

function Convert-ToPascalCase {
    param([Parameter(Mandatory = $true)][string]$Value)

    $parts = @(Get-JavaIdentifierParts $Value)
    if ($parts.Count -eq 0) {
        throw "Subsystem name must contain at least one letter or number."
    }

    return ($parts | ForEach-Object {
        $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1)
    }) -join ""
}

function Convert-ToCamelCase {
    param([Parameter(Mandatory = $true)][string]$Pascal)
    return $Pascal.Substring(0, 1).ToLowerInvariant() + $Pascal.Substring(1)
}

function Convert-ToConstantPrefix {
    param([Parameter(Mandatory = $true)][string]$RawName)
    return (@(Get-JavaIdentifierParts $RawName) | ForEach-Object { $_.ToUpperInvariant() }) -join "_"
}

function Get-StableSubsystemId {
    param([Parameter(Mandatory = $true)]$Subsystem)

    if (($Subsystem.PSObject.Properties.Name -contains "id") -and -not [string]::IsNullOrWhiteSpace($Subsystem.id)) {
        return $Subsystem.id.ToString()
    }

    return Convert-ToCamelCase (Convert-ToPascalCase $Subsystem.name)
}

function Get-SubsystemMetadata {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $pascal = Convert-ToPascalCase $Subsystem.name
    $type = $Subsystem.type.ToString().ToLowerInvariant()
    if ($type -eq "position") {
        $type = "absoluteposition"
    }
    if ($type -ne "velocity" -and $type -ne "velocitytorque" -and $type -ne "absoluteposition" -and $type -ne "relativeposition") {
        throw "Unsupported subsystem type '$($Subsystem.type)' for '$($Subsystem.name)'. Accepted values: velocity, velocityTorque, absolutePosition, relativePosition."
    }

    $subsystemClassName = switch ($type) {
        "velocity" { "VelocitySubsystem" }
        "velocitytorque" { "VelocityTorqueSubsystem" }
        "absoluteposition" { "AbsolutePositionSubsystem" }
        "relativeposition" { "RelativePositionSubsystem" }
    }

    return [pscustomobject]@{
        Id = Get-StableSubsystemId $Subsystem
        Name = $Subsystem.name
        Type = $type
        PascalName = $pascal
        CamelName = Convert-ToCamelCase $pascal
        ConstantPrefix = Convert-ToConstantPrefix $Subsystem.name
        SubsystemClassName = $subsystemClassName
        ConfigConstantName = "$(Convert-ToConstantPrefix $Subsystem.name)_CONFIG"
    }
}

function Get-NeutralModeExpression {
    param([Parameter(Mandatory = $true)][string]$Value)

    if ($Value -ieq "Coast") {
        return "NeutralModeValue.Coast"
    }
    if ($Value -ieq "Brake") {
        return "NeutralModeValue.Brake"
    }

    throw "Unsupported neutral mode '$Value'. Accepted values: Brake, Coast."
}

function Get-OptionalDoubleExpression {
    param($Value)

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace($Value.ToString())) {
        return "Optional.empty()"
    }

    $text = $Value.ToString()
    if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
        $text = "$text.0"
    }

    return "Optional.of($text)"
}

function Get-FocEnabledExpression {
    param($Subsystem)

    if ($Subsystem.PSObject.Properties.Name -contains "focEnabled" -and $null -ne $Subsystem.focEnabled) {
        return $Subsystem.focEnabled.ToString().ToLowerInvariant()
    }

    return "true"
}

function Get-TorqueFeedForwardExpression {
    param($Subsystem)

    if ($Subsystem.PSObject.Properties.Name -contains "torqueFF" -and $null -ne $Subsystem.torqueFF) {
        $text = $Subsystem.torqueFF.ToString()
        if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
            $text = "$text.0"
        }
        return $text
    }

    return "0.0"
}

function Format-IndentedList {
    param(
        [Parameter(Mandatory = $true)][string[]]$Expressions,
        [Parameter(Mandatory = $true)][string]$Indent
    )

    return ($Expressions | ForEach-Object { "$Indent$_" }) -join ",`n"
}

function Convert-MotorsToExpressions {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $motors = @($Subsystem.motors)
    if ($motors.Count -eq 0) {
        throw "Subsystem '$($Subsystem.name)' must have at least one motor."
    }

    $leader = $motors | Where-Object { $_.role -eq "leader" } | Select-Object -First 1
    if ($null -eq $leader) {
        throw "Subsystem '$($Subsystem.name)' must have one leader motor."
    }

    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"
    $leaderReversed = Get-ObjectPropertyValue $leader "reversed" $false
    $lines = @("MotorConfig.leader($($leader.id), $(Get-NeutralModeExpression $leaderNeutralMode), $($leaderReversed.ToString().ToLowerInvariant()))")
    foreach ($follower in ($motors | Where-Object { $_.role -eq "follower" })) {
        $followerNeutralMode = Get-ObjectPropertyValue $follower "neutralMode" $null
        $neutralMode = if ($null -ne $followerNeutralMode -and -not [string]::IsNullOrWhiteSpace($followerNeutralMode.ToString())) {
            $followerNeutralMode
        } else {
            $leaderNeutralMode
        }
        $followerReversed = Get-ObjectPropertyValue $follower "reversed" $false
        $lines += "MotorConfig.follower($($follower.id), $(Get-NeutralModeExpression $neutralMode), $($followerReversed.ToString().ToLowerInvariant()))"
    }

    return $lines
}

function Get-LeaderMotor {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $motors = @($Subsystem.motors)
    if ($motors.Count -eq 0) {
        throw "Subsystem '$($Subsystem.name)' must have at least one motor."
    }

    $leader = $motors | Where-Object { $_.role -eq "leader" } | Select-Object -First 1
    if ($null -eq $leader) {
        throw "Subsystem '$($Subsystem.name)' must have one leader motor."
    }

    return $leader
}

function Convert-MotorsToConstantDeclarations {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $leader = Get-LeaderMotor $Subsystem
    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"
    $leaderReversed = Get-ObjectPropertyValue $leader "reversed" $false
    $lines = @(
        "  public static final int LEADER_MOTOR_ID = $($leader.id);",
        "  public static final NeutralModeValue LEADER_NEUTRAL_MODE = $(Get-NeutralModeExpression $leaderNeutralMode);",
        "  public static final boolean LEADER_REVERSED = $($leaderReversed.ToString().ToLowerInvariant());"
    )

    $index = 1
    foreach ($follower in (@($Subsystem.motors) | Where-Object { $_.role -eq "follower" })) {
        $followerNeutralMode = Get-ObjectPropertyValue $follower "neutralMode" $null
        $neutralModeExpression = if ($null -ne $followerNeutralMode -and -not [string]::IsNullOrWhiteSpace($followerNeutralMode.ToString())) {
            Get-NeutralModeExpression $followerNeutralMode
        } else {
            "LEADER_NEUTRAL_MODE"
        }
        $followerReversed = Get-ObjectPropertyValue $follower "reversed" $false
        $lines += "  public static final int FOLLOWER_${index}_MOTOR_ID = $($follower.id);"
        $lines += "  public static final NeutralModeValue FOLLOWER_${index}_NEUTRAL_MODE = $neutralModeExpression;"
        $lines += "  public static final boolean FOLLOWER_${index}_REVERSED = $($followerReversed.ToString().ToLowerInvariant());"
        $index++
    }

    return $lines -join "`n"
}

function Convert-MotorsToConstantExpressions {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $null = Get-LeaderMotor $Subsystem
    $lines = @("MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)")

    $index = 1
    foreach ($follower in (@($Subsystem.motors) | Where-Object { $_.role -eq "follower" })) {
        $lines += "MotorConfig.follower(FOLLOWER_${index}_MOTOR_ID, FOLLOWER_${index}_NEUTRAL_MODE, FOLLOWER_${index}_REVERSED)"
        $index++
    }

    return $lines
}

function New-InteractiveMotors {
    $leaderId = Prompt-Int "Leader motor CAN ID"
    $neutral = Prompt-Enum "Leader neutral mode" @("Brake", "Coast") "Brake"
    $leaderReversed = Prompt-Boolean "Leader reversed?" $false

    $motors = @(
        [pscustomobject]@{
            role = "leader"
            id = $leaderId
            neutralMode = $neutral
            reversed = $leaderReversed
        }
    )

    $followerIds = Prompt-Value "Follower motor CAN IDs, comma-separated (blank for none)" ""
    foreach ($idText in ($followerIds -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_.Length -gt 0 })) {
        $followerId = [int]$idText
        $motors += [pscustomobject]@{
            role = "follower"
            id = $followerId
            reversed = Prompt-Boolean "Follower $followerId reversed?" $false
        }
    }

    return $motors
}

function New-InteractivePidConfig {
    if (-not (Prompt-Boolean "Configure PID/feedforward values?" $false)) {
        return [ordered]@{
            kP = "0.0"
            kI = "0.0"
            kD = "0.0"
            kG = "0.0"
            kS = $null
            kV = $null
            kA = $null
        }
    }

    return [ordered]@{
        kP = Prompt-DoubleText "kP" "0.0"
        kI = Prompt-DoubleText "kI" "0.0"
        kD = Prompt-DoubleText "kD" "0.0"
        kG = Prompt-DoubleText "kG" "0.0"
        kS = Prompt-OptionalDoubleText "kS"
        kV = Prompt-OptionalDoubleText "kV"
        kA = Prompt-OptionalDoubleText "kA"
    }
}

function New-InteractiveSubsystem {
    $rawName = Prompt-Required "Subsystem name, example shooter"
    $type = (Prompt-Enum "Subsystem type" @("velocity", "velocityTorque", "absolutePosition", "relativePosition") "velocity").ToLowerInvariant()
    $canonicalType = switch ($type) {
        "velocitytorque" { "velocityTorque" }
        "absoluteposition" { "absolutePosition" }
        "relativeposition" { "relativePosition" }
        default { $type }
    }
    $stableId = Convert-ToCamelCase (Convert-ToPascalCase $rawName)

    $subsystem = [ordered]@{
        id = $stableId
        name = $rawName
        type = $canonicalType
        motors = @(New-InteractiveMotors)
        pid = New-InteractivePidConfig
        focEnabled = Prompt-Boolean "Enable FOC?" $true
        torqueFF = if ($type -eq "velocitytorque") { Prompt-DoubleText "Torque FF" "0.0" } else { "0.0" }
        ratios = [ordered]@{
            sensorToMechanism = Prompt-DoubleText "Sensor-to-mechanism ratio" "1.0"
            rotorToSensor = Prompt-DoubleText "Rotor-to-sensor ratio" "1.0"
        }
        motionMagic = [ordered]@{}
    }

    if ($type -eq "absoluteposition") {
        $subsystem.cancoder = [ordered]@{
            id = Prompt-Int "CANcoder CAN ID"
            magnetOffset = Prompt-DoubleText "CANcoder magnet offset rotations" "0.0"
            discontinuityPoint = Prompt-DoubleText "CANcoder discontinuity point rotations" "0.5"
        }
        $subsystem.motionMagic.cruiseVelocity = Prompt-DoubleText "Motion Magic cruise velocity" "0.0"
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
        $subsystem.absolutePosition = [ordered]@{
            units = Prompt-Value "Position units" "rotations"
            default = Prompt-OptionalDoubleText "Default position"
        }
    } elseif ($type -eq "relativeposition") {
        $subsystem.motionMagic.cruiseVelocity = Prompt-DoubleText "Motion Magic cruise velocity" "0.0"
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
        $subsystem.slowMotionMagic = [ordered]@{
            cruiseVelocity = Prompt-DoubleText "Slow Motion Magic cruise velocity" "0.0"
            acceleration = Prompt-DoubleText "Slow Motion Magic acceleration" "0.0"
        }
        $subsystem.relativePosition = [ordered]@{
            units = Prompt-Value "Position units" "rotations"
            homePosition = Prompt-DoubleText "Home position" "0.0"
            forwardSoftLimit = Prompt-DoubleText "Forward soft limit" "0.0"
            reverseSoftLimit = Prompt-DoubleText "Reverse soft limit" "0.0"
            slowThreshold = Prompt-DoubleText "Slow threshold" "0.0"
            tolerance = Prompt-DoubleText "Position tolerance" "0.05"
            stopVoltage = Prompt-DoubleText "Stop voltage" "0.0"
        }
    } else {
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
    }

    return [pscustomobject]$subsystem
}

function New-DefaultSwerveConfig {
    return [pscustomobject]@{
        driver = [pscustomobject]@{
            maxSpeedCoefficient = 0.75
            velocityScale = 0.95
            maxAngularRateRadiansPerSecond = 9.42477796076938
            joystickDeadband = 0.1
            skewCompensation = -0.03
        }
        requests = [pscustomobject]@{
            maxAngularRateRadiansPerSecond = 4.71238898038469
            translationDeadbandMetersPerSecond = 0.572
            rotationalDeadbandRadiansPerSecond = 0.471238898038469
        }
        driveToPoint = [pscustomobject]@{
            maxAngularRateRadiansPerSecond = 3.141592653589793
            maxSpeedCoefficient = 0.75
            slowSpeedCoefficient = 0.1875
            staticFrictionConstant = 0.085
        }
        heading = [pscustomobject]@{
            kP = 7.0
            kI = 0.0
            kD = 0.0
        }
    }
}

function Test-IsJsonObject {
    param([AllowNull()]$Value)

    return $null -ne $Value -and
        $Value -isnot [array] -and
        $Value -is [System.Management.Automation.PSCustomObject]
}

function Get-ObjectProperty {
    param(
        [AllowNull()]$Object,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if ($null -eq $Object) {
        return $null
    }

    return $Object.PSObject.Properties[$Name]
}

function Get-ObjectPropertyValue {
    param(
        [AllowNull()]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $DefaultValue = $null
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or $null -eq $property.Value) {
        return $DefaultValue
    }

    return $property.Value
}

function Set-ObjectProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $Value
    )

    $Object | Add-Member -MemberType NoteProperty -Name $Name -Value $Value -Force
}

function Ensure-ObjectProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $DefaultValue
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or $null -eq $property.Value) {
        Set-ObjectProperty $Object $Name $DefaultValue
    }
}

function Ensure-ObjectPropertyObject {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or -not (Test-IsJsonObject $property.Value)) {
        Set-ObjectProperty $Object $Name ([pscustomobject]@{})
    }
}

function Ensure-SwerveConfig {
    param([Parameter(Mandatory = $true)]$Document)

    $defaults = New-DefaultSwerveConfig
    Ensure-ObjectPropertyObject $Document "swerve"
    Ensure-ObjectPropertyObject $Document.swerve "driver"
    Ensure-ObjectPropertyObject $Document.swerve "requests"
    Ensure-ObjectPropertyObject $Document.swerve "driveToPoint"
    Ensure-ObjectPropertyObject $Document.swerve "heading"

    Ensure-ObjectProperty $Document.swerve.driver "maxSpeedCoefficient" $defaults.driver.maxSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driver "velocityScale" $defaults.driver.velocityScale
    Ensure-ObjectProperty $Document.swerve.driver "maxAngularRateRadiansPerSecond" $defaults.driver.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.driver "joystickDeadband" $defaults.driver.joystickDeadband
    Ensure-ObjectProperty $Document.swerve.driver "skewCompensation" $defaults.driver.skewCompensation

    Ensure-ObjectProperty $Document.swerve.requests "maxAngularRateRadiansPerSecond" $defaults.requests.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.requests "translationDeadbandMetersPerSecond" $defaults.requests.translationDeadbandMetersPerSecond
    Ensure-ObjectProperty $Document.swerve.requests "rotationalDeadbandRadiansPerSecond" $defaults.requests.rotationalDeadbandRadiansPerSecond

    Ensure-ObjectProperty $Document.swerve.driveToPoint "maxAngularRateRadiansPerSecond" $defaults.driveToPoint.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.driveToPoint "maxSpeedCoefficient" $defaults.driveToPoint.maxSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driveToPoint "slowSpeedCoefficient" $defaults.driveToPoint.slowSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driveToPoint "staticFrictionConstant" $defaults.driveToPoint.staticFrictionConstant

    Ensure-ObjectProperty $Document.swerve.heading "kP" $defaults.heading.kP
    Ensure-ObjectProperty $Document.swerve.heading "kI" $defaults.heading.kI
    Ensure-ObjectProperty $Document.swerve.heading "kD" $defaults.heading.kD

    return $Document.swerve
}

function Normalize-SubsystemConfig {
    param([Parameter(Mandatory = $true)]$Subsystem)

    Ensure-ObjectProperty $Subsystem "id" (Get-StableSubsystemId $Subsystem)
    Ensure-ObjectProperty $Subsystem "motors" (@())

    $motors = @($Subsystem.motors)
    for ($index = 0; $index -lt $motors.Count; $index++) {
        $motor = $motors[$index]
        if (-not (Test-IsJsonObject $motor)) {
            continue
        }

        $defaultRole = if ($index -eq 0) { "leader" } else { "follower" }
        Ensure-ObjectProperty $motor "role" $defaultRole
        Ensure-ObjectProperty $motor "reversed" $false
    }

    $leader = $motors |
        Where-Object { (Get-ObjectPropertyValue $_ "role" "").ToString() -ieq "leader" } |
        Select-Object -First 1
    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"

    foreach ($motor in $motors) {
        if (-not (Test-IsJsonObject $motor)) {
            continue
        }

        $role = (Get-ObjectPropertyValue $motor "role" "").ToString()
        $defaultNeutralMode = if ($role -ieq "follower") { $leaderNeutralMode } else { "Brake" }
        Ensure-ObjectProperty $motor "neutralMode" $defaultNeutralMode
    }
    $Subsystem.motors = @($motors)

    Ensure-ObjectPropertyObject $Subsystem "pid"
    Ensure-ObjectProperty $Subsystem.pid "kP" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kI" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kD" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kG" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kS" $null
    Ensure-ObjectProperty $Subsystem.pid "kV" $null
    Ensure-ObjectProperty $Subsystem.pid "kA" $null

    Ensure-ObjectPropertyObject $Subsystem "ratios"
    Ensure-ObjectProperty $Subsystem.ratios "sensorToMechanism" "1.0"
    Ensure-ObjectProperty $Subsystem.ratios "rotorToSensor" "1.0"

    Ensure-ObjectPropertyObject $Subsystem "motionMagic"
    Ensure-ObjectProperty $Subsystem.motionMagic "cruiseVelocity" "0.0"
    Ensure-ObjectProperty $Subsystem.motionMagic "acceleration" "0.0"
    Ensure-ObjectProperty $Subsystem "focEnabled" $true
    Ensure-ObjectProperty $Subsystem "torqueFF" "0.0"

    $type = (Get-ObjectPropertyValue $Subsystem "type" "").ToString().ToLowerInvariant()
    if ($type -eq "position") {
        Set-ObjectProperty $Subsystem "type" "absolutePosition"
        $type = "absoluteposition"
    }

    if ($type -eq "absoluteposition") {
        $absolutePositionConfig = Get-ObjectPropertyValue $Subsystem "absolutePosition" $null
        if (-not (Test-IsJsonObject $absolutePositionConfig)) {
            $positionConfig = Get-ObjectPropertyValue $Subsystem "position" $null
            if (Test-IsJsonObject $positionConfig) {
                Set-ObjectProperty $Subsystem "absolutePosition" $positionConfig
            } else {
                Set-ObjectProperty $Subsystem "absolutePosition" ([pscustomobject]@{})
            }
        }
        Ensure-ObjectProperty $Subsystem.absolutePosition "units" "rotations"
        Ensure-ObjectProperty $Subsystem.absolutePosition "default" $null

        $cancoderConfig = Get-ObjectPropertyValue $Subsystem "cancoder" $null
        if (Test-IsJsonObject $cancoderConfig) {
            Ensure-ObjectProperty $Subsystem.cancoder "magnetOffset" "0.0"
            Ensure-ObjectProperty $Subsystem.cancoder "discontinuityPoint" "0.5"
        }
    } elseif ($type -eq "relativeposition") {
        Ensure-ObjectPropertyObject $Subsystem "slowMotionMagic"
        Ensure-ObjectProperty $Subsystem.slowMotionMagic "cruiseVelocity" "0.0"
        Ensure-ObjectProperty $Subsystem.slowMotionMagic "acceleration" "0.0"

        $relativePositionConfig = Get-ObjectPropertyValue $Subsystem "relativePosition" $null
        if (-not (Test-IsJsonObject $relativePositionConfig)) {
            $positionConfig = Get-ObjectPropertyValue $Subsystem "position" $null
            if (Test-IsJsonObject $positionConfig) {
                Set-ObjectProperty $Subsystem "relativePosition" $positionConfig
            } else {
                Set-ObjectProperty $Subsystem "relativePosition" ([pscustomobject]@{})
            }
        }
        Ensure-ObjectProperty $Subsystem.relativePosition "units" "rotations"
        Ensure-ObjectProperty $Subsystem.relativePosition "homePosition" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "forwardSoftLimit" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "reverseSoftLimit" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "slowThreshold" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "tolerance" "0.05"
        Ensure-ObjectProperty $Subsystem.relativePosition "stopVoltage" "0.0"
    }
}

function Read-SubsystemDocument {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return [pscustomobject]@{
            swerve = New-DefaultSwerveConfig
            subsystems = @()
        }
    }

    $document = Get-Content -Path $Path -Raw | ConvertFrom-Json
    if (-not (Test-IsJsonObject $document)) {
        $document = [pscustomobject]@{}
    }
    Ensure-ObjectProperty $document "subsystems" (@())
    Ensure-SwerveConfig $document | Out-Null

    $document.subsystems = @($document.subsystems)
    foreach ($subsystem in @($document.subsystems)) {
        if (Test-IsJsonObject $subsystem) {
            Normalize-SubsystemConfig $subsystem
        }
    }
    return $document
}

function Save-SubsystemDocument {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Document
    )

    Ensure-SwerveConfig $Document | Out-Null
    $Document.subsystems = @($Document.subsystems | Sort-Object { (Get-SubsystemMetadata $_).PascalName })
    $Document | ConvertTo-Json -Depth 12 | Set-Content -Path $Path -Encoding ascii
}

function Read-BindingDocument {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return [pscustomobject]@{ bindings = @() }
    }

    $document = Get-Content -Path $Path -Raw | ConvertFrom-Json
    if (-not ($document.PSObject.Properties.Name -contains "bindings")) {
        $document | Add-Member -MemberType NoteProperty -Name bindings -Value @()
    }

    $document.bindings = @($document.bindings)
    return $document
}

function Save-BindingDocument {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Document
    )

    $Document.bindings = @($Document.bindings | Sort-Object { $_.name })
    $Document | ConvertTo-Json -Depth 12 | Set-Content -Path $Path -Encoding ascii
}

function Get-SwerveConfigValue {
    param(
        [Parameter(Mandatory = $true)]$SwerveConfig,
        [Parameter(Mandatory = $true)][string[]]$Path,
        [Parameter(Mandatory = $true)]$DefaultValue
    )

    $current = $SwerveConfig
    foreach ($segment in $Path) {
        $property = Get-ObjectProperty $current $segment
        if ($null -eq $property) {
            return $DefaultValue
        }
        $current = $property.Value
    }

    if ($null -eq $current) {
        return $DefaultValue
    }

    return $current
}

function New-SwerveConstantsContent {
    param([Parameter(Mandatory = $true)]$SwerveConfig)

    $defaults = New-DefaultSwerveConfig
    $driverMaxSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driver", "maxSpeedCoefficient") $defaults.driver.maxSpeedCoefficient
    $driverVelocityScale =
        Get-SwerveConfigValue $SwerveConfig @("driver", "velocityScale") $defaults.driver.velocityScale
    $driverMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("driver", "maxAngularRateRadiansPerSecond") $defaults.driver.maxAngularRateRadiansPerSecond
    $driverJoystickDeadband =
        Get-SwerveConfigValue $SwerveConfig @("driver", "joystickDeadband") $defaults.driver.joystickDeadband
    $driverSkewCompensation =
        Get-SwerveConfigValue $SwerveConfig @("driver", "skewCompensation") $defaults.driver.skewCompensation

    $requestMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("requests", "maxAngularRateRadiansPerSecond") $defaults.requests.maxAngularRateRadiansPerSecond
    $requestTranslationDeadband =
        Get-SwerveConfigValue $SwerveConfig @("requests", "translationDeadbandMetersPerSecond") $defaults.requests.translationDeadbandMetersPerSecond
    $requestRotationalDeadband =
        Get-SwerveConfigValue $SwerveConfig @("requests", "rotationalDeadbandRadiansPerSecond") $defaults.requests.rotationalDeadbandRadiansPerSecond

    $driveToPointMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "maxAngularRateRadiansPerSecond") $defaults.driveToPoint.maxAngularRateRadiansPerSecond
    $driveToPointMaxSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "maxSpeedCoefficient") $defaults.driveToPoint.maxSpeedCoefficient
    $driveToPointSlowSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "slowSpeedCoefficient") $defaults.driveToPoint.slowSpeedCoefficient
    $driveToPointStaticFrictionConstant =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "staticFrictionConstant") $defaults.driveToPoint.staticFrictionConstant

    $headingKP = Get-SwerveConfigValue $SwerveConfig @("heading", "kP") $defaults.heading.kP
    $headingKI = Get-SwerveConfigValue $SwerveConfig @("heading", "kI") $defaults.heading.kI
    $headingKD = Get-SwerveConfigValue $SwerveConfig @("heading", "kD") $defaults.heading.kD

    return @"
package frc.robot.constants;

/**
 * PowerLib-owned swerve behavior constants.
 *
 * <p>Phoenix/Tuner X hardware constants stay in {@link TunerConstants}; these values are the driver
 * feel and heading-control defaults that Power Tool can live-tune and then save back to
 * powerlib-subsystems.json.
 */
public class SwerveConstants {
  public static final double DRIVER_MAX_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driverMaxSpeedCoefficient);
  public static final double DRIVER_VELOCITY_SCALE = $(Format-JavaDoubleLiteral $driverVelocityScale);
  public static final double DRIVER_MAX_ANGULAR_RATE_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $driverMaxAngularRate);
  public static final double DRIVER_JOYSTICK_DEADBAND = $(Format-JavaDoubleLiteral $driverJoystickDeadband);
  public static final double DRIVER_SKEW_COMPENSATION = $(Format-JavaDoubleLiteral $driverSkewCompensation);

  public static final double REQUEST_MAX_ANGULAR_RATE_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $requestMaxAngularRate);
  public static final double REQUEST_TRANSLATION_DEADBAND_METERS_PER_SECOND = $(Format-JavaDoubleLiteral $requestTranslationDeadband);
  public static final double REQUEST_ROTATIONAL_DEADBAND_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $requestRotationalDeadband);

  public static final double DRIVE_TO_POINT_MAX_ANGULAR_RATE_RADIANS_PER_SECOND =
      $(Format-JavaDoubleLiteral $driveToPointMaxAngularRate);
  public static final double DRIVE_TO_POINT_MAX_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driveToPointMaxSpeedCoefficient);
  public static final double DRIVE_TO_POINT_SLOW_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driveToPointSlowSpeedCoefficient);
  public static final double DRIVE_TO_POINT_STATIC_FRICTION_CONSTANT = $(Format-JavaDoubleLiteral $driveToPointStaticFrictionConstant);

  public static final double HEADING_KP = $(Format-JavaDoubleLiteral $headingKP);
  public static final double HEADING_KI = $(Format-JavaDoubleLiteral $headingKI);
  public static final double HEADING_KD = $(Format-JavaDoubleLiteral $headingKD);
}
"@
}

function Get-JsonPropertyValue {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $DefaultValue = $null
    )

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property -or $null -eq $property.Value) {
        return $DefaultValue
    }

    return $property.Value
}

function Upsert-SubsystemDocumentEntry {
    param(
        [Parameter(Mandatory = $true)]$Document,
        [Parameter(Mandatory = $true)]$Subsystem
    )

    $metadata = Get-SubsystemMetadata $Subsystem
    $Document.subsystems = @($Document.subsystems | Where-Object { (Get-SubsystemMetadata $_).Id -ne $metadata.Id })
    $Document.subsystems += $Subsystem
}

function New-VelocityConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final double TORQUE_FF = $(Get-TorqueFeedForwardExpression $Subsystem);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";

  public static final VelocitySubsystemConfig $($Metadata.ConfigConstantName) =
      new VelocitySubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          TORQUE_FF);

$BindingConstantsStartMarker
$BindingConstantsEndMarker

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function New-AbsolutePositionConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "
    $absolutePositionConfig = if (($Subsystem.PSObject.Properties.Name -contains "absolutePosition") -and $null -ne $Subsystem.absolutePosition) {
        $Subsystem.absolutePosition
    } else {
        $Subsystem.position
    }

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.AbsolutePositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final int CANCODER_ID = $($Subsystem.cancoder.id);
  public static final double CANCODER_MAGNET_OFFSET = $($Subsystem.cancoder.magnetOffset);
  public static final double CANCODER_DISCONTINUITY_POINT = $($Subsystem.cancoder.discontinuityPoint);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";
  public static final String POSITION_UNITS = "$($absolutePositionConfig.units)";
  public static final Optional<Double> DEFAULT_POSITION = $(Get-OptionalDoubleExpression $absolutePositionConfig.default);

  public static final AbsolutePositionSubsystemConfig $($Metadata.ConfigConstantName) =
      new AbsolutePositionSubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new CancoderConfig(CANCODER_ID, CANCODER_MAGNET_OFFSET, CANCODER_DISCONTINUITY_POINT),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          DEFAULT_POSITION);

$BindingConstantsStartMarker
$BindingConstantsEndMarker

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function New-RelativePositionConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.RelativePositionSubsystemConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final double SLOW_MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.slowMotionMagic.cruiseVelocity);
  public static final double SLOW_MOTION_MAGIC_ACCELERATION = $($Subsystem.slowMotionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";
  public static final String POSITION_UNITS = "$($Subsystem.relativePosition.units)";
  public static final double HOME_POSITION = $($Subsystem.relativePosition.homePosition);
  public static final double FORWARD_SOFT_LIMIT = $($Subsystem.relativePosition.forwardSoftLimit);
  public static final double REVERSE_SOFT_LIMIT = $($Subsystem.relativePosition.reverseSoftLimit);
  public static final double SLOW_THRESHOLD = $($Subsystem.relativePosition.slowThreshold);
  public static final double POSITION_TOLERANCE = $($Subsystem.relativePosition.tolerance);
  public static final double STOP_VOLTAGE = $($Subsystem.relativePosition.stopVoltage);

  public static final RelativePositionSubsystemConfig $($Metadata.ConfigConstantName) =
      new RelativePositionSubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          new MotionMagicConfig(SLOW_MOTION_MAGIC_CRUISE_VELOCITY, SLOW_MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          HOME_POSITION,
          FORWARD_SOFT_LIMIT,
          REVERSE_SOFT_LIMIT,
          SLOW_THRESHOLD,
          POSITION_TOLERANCE,
          STOP_VOLTAGE);

$BindingConstantsStartMarker
$BindingConstantsEndMarker

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function Ensure-ConstantsMarkers {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $content = Get-Content -Path $ConstantsPath -Raw
    if ($content.Contains($ConstantsStartMarker) -and $content.Contains($ConstantsEndMarker)) {
        return
    }

    $index = $content.LastIndexOf("}")
    if ($index -lt 0) {
        throw "Could not find closing brace in Constants.java."
    }

    $markers = "$ConstantsStartMarker`n$ConstantsEndMarker`n"
    $updated = $content.Substring(0, $index).TrimEnd() + "`n`n$markers}"
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Remove-UnmarkedGeneratedConstants {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $lines = @(Get-Content -Path $ConstantsPath)
    $kept = @()
    foreach ($line in $lines) {
        $match = [regex]::Match($line, "^\s*public static final class\s+([A-Za-z0-9_]+)\s+extends\s+frc\.robot\.constants\.[A-Za-z0-9_]+Constants\s+\{\}\s*$")
        if ($match.Success -and -not ($BuiltInConstantNames -contains $match.Groups[1].Value)) {
            continue
        }
        $kept += $line
    }

    Set-Content -Path $ConstantsPath -Value ($kept -join "`n") -Encoding ascii
}

function Rewrite-ConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$ConstantsPath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    Ensure-ConstantsMarkers $ConstantsPath
    Remove-UnmarkedGeneratedConstants $ConstantsPath
    Ensure-ConstantsMarkers $ConstantsPath

    $content = Get-Content -Path $ConstantsPath -Raw
    $start = $content.IndexOf($ConstantsStartMarker) + $ConstantsStartMarker.Length
    $end = $content.IndexOf($ConstantsEndMarker)
    $entries = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $entries += "  public static final class $($metadata.PascalName) extends frc.robot.constants.$($metadata.PascalName)Constants {}"
    }

    $block = if ($entries.Count -eq 0) { "" } else { "`n" + ($entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Rewrite-StateMachineBlock {
    param(
        [Parameter(Mandatory = $true)][string]$StateMachinePath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $content = Get-Content -Path $StateMachinePath -Raw
    if (-not $content.Contains($StateMachineStartMarker) -or -not $content.Contains($StateMachineEndMarker)) {
        throw "Could not find POWERLIB GENERATED SUBSYSTEMS markers in StateMachine.java. Re-run the installer or add the DO NOT DELETE markers manually."
    }

    $fields = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $fields += "  public final $($metadata.SubsystemClassName) $($metadata.CamelName) = new $($metadata.SubsystemClassName)(Constants.$($metadata.PascalName).$($metadata.ConfigConstantName));"
    }

    $start = $content.IndexOf($StateMachineStartMarker) + $StateMachineStartMarker.Length
    $end = $content.IndexOf($StateMachineEndMarker)
    $block = if ($fields.Count -eq 0) { "`n" } else { "`n" + ($fields -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $StateMachinePath -Value $updated -Encoding ascii
}

function Get-PreservedCustomConstantsBlock {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return $null
    }

    $content = Get-Content -Path $Path -Raw
    if (-not $content.Contains($CustomConstantsStartMarker) -or -not $content.Contains($CustomConstantsEndMarker)) {
        return $null
    }

    $start = $content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $content.IndexOf($CustomConstantsEndMarker)
    return $content.Substring($start, $end - $start).Trim("`r", "`n")
}

function Get-SubsystemIdFromGeneratedContent {
    param([Parameter(Mandatory = $true)][string]$Content)

    foreach ($line in ($Content -split "`r?`n")) {
        if ($line.StartsWith($SubsystemIdMarkerPrefix)) {
            return $line.Substring($SubsystemIdMarkerPrefix.Length).Trim()
        }
    }

    return $null
}

function Get-CustomConstantsBySubsystemId {
    param([Parameter(Mandatory = $true)][string]$ConstantsDir)

    $customBlocks = @{}
    if (-not (Test-Path $ConstantsDir)) {
        return $customBlocks
    }

    Get-ChildItem -Path $ConstantsDir -Filter "*Constants.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw
        if (-not $content.Contains($GeneratedFileMarker)) {
            return
        }

        $id = Get-SubsystemIdFromGeneratedContent $content
        if (-not [string]::IsNullOrWhiteSpace($id)) {
            $customBlock = Get-PreservedCustomConstantsBlock $_.FullName
            if (-not [string]::IsNullOrWhiteSpace($customBlock)) {
                $customBlocks[$id] = $customBlock
            }
        }
    }

    return $customBlocks
}

function Set-CustomConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [AllowNull()][string]$CustomContent
    )

    if ([string]::IsNullOrWhiteSpace($CustomContent)) {
        return $Content
    }

    $start = $Content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $Content.IndexOf($CustomConstantsEndMarker)
    if ($start -lt $CustomConstantsStartMarker.Length -or $end -lt 0) {
        return $Content
    }

    return $Content.Substring(0, $start) + "`n" + $CustomContent.Trim("`r", "`n") + "`n" + $Content.Substring($end)
}

function Write-ConstantsFile {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata,
        [Parameter(Mandatory = $true)]$CustomBlocksById
    )

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    New-Item -ItemType Directory -Force -Path $constantsDir | Out-Null

    $outputFile = Join-Path $constantsDir "$($Metadata.PascalName)Constants.java"
    $customContent = if ($CustomBlocksById.ContainsKey($Metadata.Id)) {
        $CustomBlocksById[$Metadata.Id]
    } else {
        Get-PreservedCustomConstantsBlock $outputFile
    }
    $content = switch ($Metadata.Type) {
        "velocity" { New-VelocityConstantsContent $Subsystem $Metadata }
        "velocitytorque" { New-VelocityConstantsContent $Subsystem $Metadata }
        "absoluteposition" { New-AbsolutePositionConstantsContent $Subsystem $Metadata }
        "relativeposition" { New-RelativePositionConstantsContent $Subsystem $Metadata }
    }
    $content = Set-CustomConstantsBlock $content $customContent

    Set-Content -Path $outputFile -Value $content -Encoding ascii
    return $outputFile
}

function Write-SwerveConstantsFile {
    param([Parameter(Mandatory = $true)]$SwerveConfig)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    New-Item -ItemType Directory -Force -Path $constantsDir | Out-Null

    $outputFile = Join-Path $constantsDir "SwerveConstants.java"
    Set-Content -Path $outputFile -Value (New-SwerveConstantsContent $SwerveConfig) -Encoding ascii
    return $outputFile
}

function New-VelocityCharacterizationContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    return @"
package frc.robot.characterization;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import static edu.wpi.first.units.Units.Radians;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.powerlib.subsystems.VelocitySubsystem;

public class $($Metadata.PascalName)Characterization {
  private final VelocitySubsystem subsystem;
  private final SysIdRoutine routine;
  private final double[] lastVoltage = {0};

  public $($Metadata.PascalName)Characterization(VelocitySubsystem subsystem) {
    this.subsystem = subsystem;
    this.routine =
        new SysIdRoutine(
            new SysIdRoutine.Config(
                null,
                Volts.of(4),
                null,
                state -> SignalLogger.writeString("SysId$($Metadata.PascalName)_State", state.toString())),
            new SysIdRoutine.Mechanism(
                voltage -> {
                  lastVoltage[0] = voltage.in(Volts);
                  subsystem.setVoltage(voltage.in(Volts));
                },
                log -> {
                  var motor = subsystem.getVelocityMotor();
                  if (motor == null) {
                    return;
                  }
                  double posRot = motor.getRotorPosition().getValueAsDouble();
                  double velRps = motor.getRotorVelocity().getValueAsDouble();
                  log
                      .motor("$($Metadata.PascalName)")
                      .voltage(Volts.of(lastVoltage[0]))
                      .angularPosition(Radians.of(posRot * 2 * Math.PI))
                      .angularVelocity(RadiansPerSecond.of(velRps * 2 * Math.PI));
                },
                subsystem,
                "$($Metadata.PascalName)"));
  }

  public Command quasistaticForward() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kForward));
  }

  public Command quasistaticReverse() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kReverse));
  }

  public Command dynamicForward() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kForward));
  }

  public Command dynamicReverse() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kReverse));
  }

  private Command withLogging(Command command) {
    return Commands.sequence(
        Commands.runOnce(() -> SignalLogger.start()),
        command,
        Commands.runOnce(() -> SignalLogger.stop()));
  }
}
"@
}

function Write-CharacterizationFile {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    if ($Metadata.Type -ne "velocity" -and $Metadata.Type -ne "velocitytorque") {
        return $null
    }

    $characterizationDir = Join-Path (Get-Location) "src/main/java/frc/robot/characterization"
    New-Item -ItemType Directory -Force -Path $characterizationDir | Out-Null

    $outputFile = Join-Path $characterizationDir "$($Metadata.PascalName)Characterization.java"
    Set-Content -Path $outputFile -Value (New-VelocityCharacterizationContent $Subsystem $Metadata) -Encoding ascii
    return $outputFile
}

function Ensure-PowerDashboardRawNetworkTablesSupport {
    param([Parameter(Mandatory = $true)][string]$PowerDashboardPath)

    $content = Get-Content -Path $PowerDashboardPath -Raw
    if ($content.Contains("registerCharacterizationCommand(") -and $content.Contains('getSubTable("Subsystems")') -and $content.Contains('getSubTable("Tuning")') -and $content.Contains("RequestedEnabled") -and $content.Contains("TUNING_MODE_SYNC_INTERVAL_SECONDS") -and -not $content.Contains("SmartDashboard")) {
        return
    }

    $rawPowerDashboard = @'
// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.powerlib.PowerRobotContainer;
import java.util.HashMap;
import java.util.Map;

public class PowerDashboard extends SubsystemBase {
  private static final double TUNING_MODE_SYNC_INTERVAL_SECONDS = 1.0;

  private final StateMachine stateMachine;
  private final NetworkTable subsystemsTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Subsystems");
  private final NetworkTable commandsTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Commands");
  private final NetworkTable tuningTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Tuning");
  private final NetworkTableEntry tuningEnabledEntry = tuningTable.getEntry("Enabled");
  private final NetworkTableEntry tuningRequestedEntry = tuningTable.getEntry("RequestedEnabled");
  private final NetworkTable characterizationTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Characterization");
  private final Map<String, CharacterizationCommandBinding> characterizationCommands = new HashMap<>();
  private double nextTuningModeSyncTime = 0.0;

  public PowerDashboard(StateMachine stateMachine) {
    this.stateMachine = stateMachine;
    initCharacterizationRoutines();
  }

  private void initCharacterizationRoutines() {
    // POWERLIB GENERATED CHARACTERIZATION START - DO NOT DELETE
    // POWERLIB GENERATED CHARACTERIZATION END - DO NOT DELETE
  }

  @Override
  public void periodic() {
    syncTuningMode();
    publishSubsystemData();
    syncSubsystemVariables();
    syncCommandVariables();
    pollCharacterizationCommands();
  }

  private void syncTuningMode() {
    double now = Timer.getFPGATimestamp();
    if (now < nextTuningModeSyncTime) {
      return;
    }

    nextTuningModeSyncTime = now + TUNING_MODE_SYNC_INTERVAL_SECONDS;
    boolean currentEnabled = PowerRobotContainer.isTuningEnabled();
    boolean requestedEnabled = tuningRequestedEntry.getBoolean(currentEnabled);
    PowerRobotContainer.setTuningEnabled(requestedEnabled);
    tuningEnabledEntry.setBoolean(requestedEnabled);
  }

  private void publishSubsystemData() {
    new java.util.HashMap<>(PowerRobotContainer.getAllSubsystemData())
        .forEach(
            (subsystemName, values) -> {
              NetworkTable dataTable = subsystemsTable.getSubTable(subsystemName).getSubTable("Data");
              new java.util.HashMap<>(values).forEach((key, value) -> publishValue(dataTable, key, value));
            });
  }

  private void syncSubsystemVariables() {
    syncVariables(
        PowerRobotContainer.getAllSubsystemVariables(),
        subsystemsTable,
        PowerRobotContainer::updateSubsystemVariable);
  }

  private void syncCommandVariables() {
    syncVariables(
        PowerRobotContainer.getAllCommandVariables(),
        commandsTable,
        PowerRobotContainer::updateCommandVariable);
  }

  private void syncVariables(
      Map<String, Map<String, Object>> variablesByOwner,
      NetworkTable ownerTable,
      VariableUpdater updater) {
    new java.util.HashMap<>(variablesByOwner)
        .forEach(
            (ownerName, variables) -> {
              NetworkTable variablesTable = ownerTable.getSubTable(ownerName).getSubTable("Variables");
              new java.util.HashMap<>(variables)
                  .forEach(
                      (key, defaultValue) -> {
                        Object value =
                            syncVariable(
                                variablesTable.getEntry(key),
                                defaultValue,
                                PowerRobotContainer.isTuningEnabled());
                        updater.update(ownerName, key, value);
                      });
            });
  }

  private Object syncVariable(NetworkTableEntry entry, Object defaultValue, boolean tuningEnabled) {
    if (defaultValue instanceof Boolean) {
      boolean fallback = (Boolean) defaultValue;
      if (!entry.exists()) {
        entry.setBoolean(fallback);
      }
      if (!tuningEnabled) {
        return fallback;
      }
      return entry.getBoolean(fallback);
    }

    if (defaultValue instanceof Number) {
      double fallback = ((Number) defaultValue).doubleValue();
      if (!entry.exists()) {
        entry.setDouble(fallback);
      }
      if (!tuningEnabled) {
        return fallback;
      }
      return entry.getDouble(fallback);
    }

    String fallback = defaultValue == null ? "" : defaultValue.toString();
    if (!entry.exists()) {
      entry.setString(fallback);
    }
    if (!tuningEnabled) {
      return fallback;
    }
    return entry.getString(fallback);
  }

  private void publishValue(NetworkTable table, String key, Object value) {
    NetworkTableEntry entry = table.getEntry(key);
    if (value instanceof Boolean) {
      entry.setBoolean((Boolean) value);
      return;
    }

    if (value instanceof Number) {
      entry.setDouble(((Number) value).doubleValue());
      return;
    }

    entry.setString(value == null ? "" : value.toString());
  }

  private interface VariableUpdater {
    void update(String ownerName, String key, Object value);
  }

  private void registerCharacterizationCommand(String subsystemName, String commandName, Command command) {
    NetworkTable commandTable = characterizationTable.getSubTable(subsystemName).getSubTable(commandName);
    NetworkTableEntry requestEntry = commandTable.getEntry("request");
    NetworkTableEntry runningEntry = commandTable.getEntry("running");

    commandTable.getEntry(".type").setString("PowerLibCommand");
    commandTable.getEntry("name").setString(commandName);
    requestEntry.setBoolean(false);
    runningEntry.setBoolean(false);
    characterizationCommands.put(
        subsystemName + "/" + commandName,
        new CharacterizationCommandBinding(command, requestEntry, runningEntry));
  }

  private void pollCharacterizationCommands() {
    CommandScheduler scheduler = CommandScheduler.getInstance();
    characterizationCommands.values().forEach(
        binding -> {
          if (binding.requestEntry.getBoolean(false)) {
            binding.requestEntry.setBoolean(false);
            if (!scheduler.isScheduled(binding.command)) {
              scheduler.schedule(binding.command);
            }
          }

          binding.runningEntry.setBoolean(scheduler.isScheduled(binding.command));
        });
  }

  private static class CharacterizationCommandBinding {
    private final Command command;
    private final NetworkTableEntry requestEntry;
    private final NetworkTableEntry runningEntry;

    private CharacterizationCommandBinding(
        Command command, NetworkTableEntry requestEntry, NetworkTableEntry runningEntry) {
      this.command = command;
      this.requestEntry = requestEntry;
      this.runningEntry = runningEntry;
    }
  }
}
'@

    Set-Content -Path $PowerDashboardPath -Value $rawPowerDashboard -Encoding ascii
}

function Rewrite-PowerDashboardCharacterizationBlock {
    param(
        [Parameter(Mandatory = $true)][string]$PowerDashboardPath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $content = Get-Content -Path $PowerDashboardPath -Raw
    if (-not $content.Contains($CharacterizationStartMarker) -or -not $content.Contains($CharacterizationEndMarker)) {
        throw "Could not find POWERLIB GENERATED CHARACTERIZATION markers in PowerDashboard.java. Re-run the installer or add the DO NOT DELETE markers manually."
    }

    $velocitySubsystems = @($Subsystems | Where-Object {
        $type = $_.type.ToString().ToLowerInvariant()
        $type -eq "velocity" -or $type -eq "velocitytorque"
    })
    $imports = @($velocitySubsystems | ForEach-Object {
        $metadata = Get-SubsystemMetadata $_
        "import frc.robot.characterization.$($metadata.PascalName)Characterization;"
    })

    $content = [regex]::Replace(
        $content,
        "(?m)^import frc\.robot\.characterization\.[A-Za-z0-9_]+Characterization;\r?\n",
        ""
    )

    if ($imports.Count -gt 0) {
        $lastImportMatch = [regex]::Matches($content, "(?m)^import .+;\r?$") | Select-Object -Last 1
        if ($null -ne $lastImportMatch) {
            $insertAt = $lastImportMatch.Index + $lastImportMatch.Length
            $content = $content.Substring(0, $insertAt) + "`n" + ($imports -join "`n") + $content.Substring($insertAt)
        }
    }

    $entries = @()
    foreach ($subsystem in $velocitySubsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $fieldName = "$($metadata.CamelName)Characterization"
        $entries += "    var $fieldName = new $($metadata.PascalName)Characterization(stateMachine.$($metadata.CamelName));"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Quasistatic Forward`", $fieldName.quasistaticForward());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Quasistatic Reverse`", $fieldName.quasistaticReverse());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Dynamic Forward`", $fieldName.dynamicForward());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Dynamic Reverse`", $fieldName.dynamicReverse());"
    }

    $start = $content.IndexOf($CharacterizationStartMarker) + $CharacterizationStartMarker.Length
    $end = $content.IndexOf($CharacterizationEndMarker)
    $block = if ($entries.Count -eq 0) { "`n" } else { "`n" + ($entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $PowerDashboardPath -Value $updated -Encoding ascii
}

function Remove-DeletedGeneratedFiles {
    param([Parameter(Mandatory = $true)]$Subsystems)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"

    $wantedFiles = @{}
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $wantedFiles["$($metadata.PascalName)Constants.java"] = $true
    }

    if (Test-Path $constantsDir) {
        Get-ChildItem -Path $constantsDir -Filter "*Constants.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarker) -and -not $wantedFiles.ContainsKey($_.Name)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted removed subsystem constants $($_.Name)"
            }
        }
    }

    Remove-LegacyGeneratedSubsystemFiles
}

function Remove-LegacyGeneratedSubsystemFiles {
    $subsystemsDir = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems"
    if (Test-Path $subsystemsDir) {
        Get-ChildItem -Path $subsystemsDir -Filter "*.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarker)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted legacy generated subsystem $($_.Name)"
            }
        }
    }

    $ioDir = Join-Path $subsystemsDir "io"
    if (Test-Path $ioDir) {
        Get-ChildItem -Path $ioDir -Filter "*.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarker)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted legacy generated subsystem IO $($_.Name)"
            }
        }
    }
}

function Remove-StaleCharacterizationFiles {
    param([Parameter(Mandatory = $true)]$Subsystems)

    $characterizationDir = Join-Path (Get-Location) "src/main/java/frc/robot/characterization"
    if (-not (Test-Path $characterizationDir)) {
        return
    }

    $wantedFiles = @{}
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        if ($metadata.Type -eq "velocity" -or $metadata.Type -eq "velocitytorque") {
            $wantedFiles["$($metadata.PascalName)Characterization.java"] = $true
        }
    }

    Get-ChildItem -Path $characterizationDir -Filter "*Characterization.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw
        if ($content.Contains($GeneratedFileMarker) -and -not $wantedFiles.ContainsKey($_.Name)) {
            Remove-Item -LiteralPath $_.FullName -Force
            Write-Host "Deleted stale characterization $($_.Name)"
        }
    }
}

function Find-SubsystemById {
    param(
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$Id
    )

    foreach ($subsystem in @($Subsystems)) {
        if ((Get-SubsystemMetadata $subsystem).Id -eq $Id) {
            return $subsystem
        }
    }

    throw "Binding references unknown subsystem id '$Id'."
}

function Get-BindingMethodNeedsValue {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)][string]$Method
    )

    $type = (Get-SubsystemMetadata $Subsystem).Type
    $valueMethods = switch ($type) {
        "absoluteposition" { @("setPositionRotations", "setPositionDegrees", "setVoltage") }
        "relativeposition" { @("setPosition", "setPositionRotations", "setVoltage") }
        default { @("setVelocity", "setVoltage") }
    }
    $voidMethods = switch ($type) {
        "absoluteposition" { @("stopPosition") }
        "relativeposition" { @("zeroEncoder") }
        default { @("stopVelocity", "brake") }
    }

    if ($valueMethods -contains $Method) {
        return $true
    }
    if ($voidMethods -contains $Method) {
        return $false
    }

    throw "Unsupported method '$Method' for subsystem '$($Subsystem.name)' of type '$type'."
}

function Convert-ToJavaIdentifier {
    param(
        [Parameter(Mandatory = $true)][string]$Value,
        [string]$Fallback = "bindingValue"
    )

    $parts = @(Get-JavaIdentifierParts $Value)
    if ($parts.Count -eq 0) {
        $parts = @(Get-JavaIdentifierParts $Fallback)
    }

    $identifier = ($parts | ForEach-Object {
        $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1).ToLowerInvariant()
    }) -join ""
    return Convert-ToCamelCase $identifier
}

function Convert-ToJavaConstantName {
    param([Parameter(Mandatory = $true)][string]$Value)

    $parts = @(Get-JavaIdentifierParts $Value)
    if ($parts.Count -eq 0) {
        throw "Binding constant name '$Value' is not a valid Java identifier."
    }

    return ($parts | ForEach-Object { $_.ToUpperInvariant() }) -join "_"
}

function Convert-ToJavaStringLiteral {
    param([AllowNull()][string]$Value)

    if ($null -eq $Value) {
        return '""'
    }

    return '"' + $Value.Replace('\', '\\').Replace('"', '\"') + '"'
}

function Format-JavaDoubleLiteral {
    param([Parameter(Mandatory = $true)]$Value)

    $text = $Value.ToString()
    if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
        $text = "$text.0"
    }

    return $text
}

function Get-BindingControllerExpression {
    param([Parameter(Mandatory = $true)][string]$Controller)

    if ($Controller -eq "driver") {
        return "driverController"
    }
    if ($Controller -eq "operator") {
        return "operatorController"
    }

    throw "Unsupported binding controller '$Controller'. Accepted values: driver, operator."
}

function Get-BindingTriggerExpression {
    param(
        [Parameter(Mandatory = $true)][string]$Controller,
        [Parameter(Mandatory = $true)][string]$InputName
    )

    $accepted = @(
        "a",
        "b",
        "x",
        "y",
        "leftBumper",
        "rightBumper",
        "leftTrigger",
        "rightTrigger",
        "povUp",
        "povDown",
        "povLeft",
        "povRight",
        "start",
        "back"
    )
    if (-not ($accepted -contains $InputName)) {
        throw "Unsupported binding input '$InputName'. Accepted values: $($accepted -join ', ')."
    }

    $threshold = if ($InputName -eq "leftTrigger" -or $InputName -eq "rightTrigger") { "0.5" } else { "" }
    return "$(Get-BindingControllerExpression $Controller).$InputName($threshold)"
}

function Get-BindingEventName {
    param([Parameter(Mandatory = $true)][string]$Event)

    $accepted = @("onTrue", "onFalse", "whileTrue", "toggleOnTrue")
    if (-not ($accepted -contains $Event)) {
        throw "Unsupported binding event '$Event'. Accepted values: $($accepted -join ', ')."
    }

    return $Event
}

function Ensure-BindingConstantsMarkers {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $content = Get-Content -Path $ConstantsPath -Raw
    if ($content.Contains($BindingConstantsStartMarker) -and $content.Contains($BindingConstantsEndMarker)) {
        return
    }

    $insertAt = $content.IndexOf($CustomConstantsStartMarker)
    if ($insertAt -lt 0) {
        $insertAt = $content.LastIndexOf("}")
    }
    if ($insertAt -lt 0) {
        throw "Could not find a place to insert binding constants in $ConstantsPath."
    }

    $markers = "$BindingConstantsStartMarker`n$BindingConstantsEndMarker`n`n"
    $updated = $content.Substring(0, $insertAt).TrimEnd() + "`n`n$markers" + $content.Substring($insertAt)
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Rewrite-BindingConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$ConstantsPath,
        [AllowEmptyCollection()][string[]]$Entries = @()
    )

    Ensure-BindingConstantsMarkers $ConstantsPath
    $content = Get-Content -Path $ConstantsPath -Raw
    $start = $content.IndexOf($BindingConstantsStartMarker) + $BindingConstantsStartMarker.Length
    $end = $content.IndexOf($BindingConstantsEndMarker)
    $block = if ($Entries.Count -eq 0) { "`n" } else { "`n" + ($Entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Get-BindingCommandKind {
    param([Parameter(Mandatory = $true)]$Command)

    $kind = (Get-JsonPropertyValue $Command "kind" "function").ToString()
    if ($kind -eq "sequence" -or $kind -eq "parallel" -or $kind -eq "parallelRace" -or $kind -eq "function" -or $kind -eq "wait") {
        return $kind
    }

    return "function"
}

function Get-BindingCommandVariableKey {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $kind = Get-BindingCommandKind $Command
    $constantProperty = Get-JsonPropertyValue $Command "constantName"
    if ([string]::IsNullOrWhiteSpace($constantProperty)) {
        throw "$Description needs a constant name."
    }

    $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
    if ($kind -eq "wait") {
        return "Wait/$constantName"
    }

    $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
    $method = (Get-JsonPropertyValue $Command "method" "").ToString()
    $subsystem = Find-SubsystemById $Subsystems $subsystemId
    $metadata = Get-SubsystemMetadata $subsystem
    return "$($metadata.PascalName)/$method/$constantName"
}

function New-InstantBindingCommandCall {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
    $method = (Get-JsonPropertyValue $Command "method" "").ToString()
    $subsystem = Find-SubsystemById $Subsystems $subsystemId
    $metadata = Get-SubsystemMetadata $subsystem
    $needsValue = Get-BindingMethodNeedsValue $subsystem $method
    $argument = ""
    if ($needsValue) {
        $constantProperty = Get-JsonPropertyValue $Command "constantName"
        if ([string]::IsNullOrWhiteSpace($constantProperty)) {
            throw "Binding command '$method' for subsystem '$($metadata.Name)' needs a constant name."
        }
        $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
        $fallback = "Constants.$($metadata.PascalName).$constantName"
        $variableKey = Get-BindingCommandVariableKey $Command $Subsystems "Binding command '$method'"
        $argument = "PowerRobotContainer.getCommandVariable($(Convert-ToJavaStringLiteral $CommandOwner), $(Convert-ToJavaStringLiteral $variableKey), $fallback)"
    }

    $call = if ($needsValue) {
        "stateMachine.$($metadata.CamelName).$method($argument);"
    } else {
        "stateMachine.$($metadata.CamelName).$method();"
    }

    return [pscustomobject]@{
        Call = $call
        Requirement = "stateMachine.$($metadata.CamelName)"
    }
}

function Get-BindingConstantReference {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
    $subsystem = Find-SubsystemById $Subsystems $subsystemId
    $metadata = Get-SubsystemMetadata $subsystem
    $constantProperty = Get-JsonPropertyValue $Command "constantName"
    if ([string]::IsNullOrWhiteSpace($constantProperty)) {
        throw "$Description needs a constant name."
    }
    $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
    return "Constants.$($metadata.PascalName).$constantName"
}

function New-InstantBindingCommandExpression {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $commandCall = New-InstantBindingCommandCall $Command $Subsystems $CommandOwner
    return "new InstantCommand(() -> { $($commandCall.Call) }, $($commandCall.Requirement))"
}

function New-RunBindingCommandExpression {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $commandCall = New-InstantBindingCommandCall $Command $Subsystems $CommandOwner
    return "Commands.run(() -> { $($commandCall.Call) }, $($commandCall.Requirement))"
}

function New-InstantBindingGroupExpression {
    param(
        [Parameter(Mandatory = $true)]$Commands,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $commandCalls = @($Commands | ForEach-Object { New-InstantBindingCommandCall $_ $Subsystems $CommandOwner })
    $requirements = @($commandCalls | ForEach-Object { $_.Requirement } | Select-Object -Unique)
    $calls = ($commandCalls | ForEach-Object { $_.Call }) -join " "
    return "new InstantCommand(() -> { $calls }, $($requirements -join ', '))"
}

function Test-BindingCommandGroupContainsKind {
    param(
        [Parameter(Mandatory = $true)]$Commands,
        [Parameter(Mandatory = $true)][string]$Kind
    )

    foreach ($command in @($Commands)) {
        $commandKind = Get-BindingCommandKind $command
        if ($commandKind -eq $Kind) {
            return $true
        }
        if ($commandKind -eq "sequence" -or $commandKind -eq "parallel" -or $commandKind -eq "parallelRace") {
            if (Test-BindingCommandGroupContainsKind (Get-JsonPropertyValue $command "children" @()) $Kind) {
                return $true
            }
        }
    }

    return $false
}

function New-BindingCommandExpression {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $kind = Get-BindingCommandKind $Command
    if ($kind -eq "function") {
        return New-InstantBindingCommandExpression $Command $Subsystems $CommandOwner
    }
    if ($kind -eq "wait") {
        $fallback = Get-BindingConstantReference $Command $Subsystems 'Wait command'
        $variableKey = Get-BindingCommandVariableKey $Command $Subsystems 'Wait command'
        return "Commands.waitSeconds(PowerRobotContainer.getCommandVariable($(Convert-ToJavaStringLiteral $CommandOwner), $(Convert-ToJavaStringLiteral $variableKey), $fallback))"
    }

    $children = @(Get-JsonPropertyValue $Command "children" @())
    if ($children.Count -eq 0) {
        throw "Binding command group '$kind' must contain at least one child command."
    }

    if ($kind -eq "sequence") {
        $childExpressions = @($children | ForEach-Object { New-BindingCommandExpression $_ $Subsystems $CommandOwner })
        return "new SequentialCommandGroup($($childExpressions -join ', '))"
    }
    if ($kind -eq "parallel") {
        $childExpressions = @($children | ForEach-Object { New-BindingCommandExpression $_ $Subsystems $CommandOwner })
        return "new ParallelCommandGroup($($childExpressions -join ', '))"
    }

    $raceContainsWait = Test-BindingCommandGroupContainsKind $children "wait"
    $childExpressions = @($children | ForEach-Object {
        if ($raceContainsWait -and (Get-BindingCommandKind $_) -eq "function") {
            New-RunBindingCommandExpression $_ $Subsystems $CommandOwner
        } else {
            New-BindingCommandExpression $_ $Subsystems $CommandOwner
        }
    })
    return "new ParallelRaceGroup($($childExpressions -join ', '))"
}

function Get-BindingCommandVariableDefaultLines {
    param(
        [Parameter(Mandatory = $true)]$Command,
        [Parameter(Mandatory = $true)]$Subsystems,
        [Parameter(Mandatory = $true)][string]$CommandOwner
    )

    $kind = Get-BindingCommandKind $Command
    if ($kind -eq "function") {
        $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
        $method = (Get-JsonPropertyValue $Command "method" "").ToString()
        $subsystem = Find-SubsystemById $Subsystems $subsystemId
        if (-not (Get-BindingMethodNeedsValue $subsystem $method)) {
            return @()
        }

        $metadata = Get-SubsystemMetadata $subsystem
        $constantProperty = Get-JsonPropertyValue $Command "constantName"
        if ([string]::IsNullOrWhiteSpace($constantProperty)) {
            throw "Binding command '$method' for subsystem '$($metadata.Name)' needs a constant name."
        }

        $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
        $variableKey = Get-BindingCommandVariableKey $Command $Subsystems "Binding command '$method'"
        return @("    PowerRobotContainer.setCommandVariableDefault($(Convert-ToJavaStringLiteral $CommandOwner), $(Convert-ToJavaStringLiteral $variableKey), Constants.$($metadata.PascalName).$constantName);")
    }

    if ($kind -eq "wait") {
        $fallback = Get-BindingConstantReference $Command $Subsystems 'Wait command'
        $variableKey = Get-BindingCommandVariableKey $Command $Subsystems 'Wait command'
        return @("    PowerRobotContainer.setCommandVariableDefault($(Convert-ToJavaStringLiteral $CommandOwner), $(Convert-ToJavaStringLiteral $variableKey), $fallback);")
    }

    $lines = @()
    foreach ($child in @(Get-JsonPropertyValue $Command "children" @())) {
        $lines += @(Get-BindingCommandVariableDefaultLines $child $Subsystems $CommandOwner)
    }

    return $lines
}

function Write-PowerButtonBindingsFile {
    param(
        [Parameter(Mandatory = $true)]$Bindings,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $outputFile = Join-Path (Get-Location) "src/main/java/frc/robot/PowerButtonBindings.java"
    $lines = @()
    $lines += "package frc.robot;"
    $lines += ""
    $lines += "$GeneratedFileMarker"
    $lines += ""
    $lines += "import edu.wpi.first.wpilibj2.command.Command;"
    $lines += "import edu.wpi.first.wpilibj2.command.Commands;"
    $lines += "import edu.wpi.first.wpilibj2.command.InstantCommand;"
    $lines += "import edu.wpi.first.wpilibj2.command.ParallelCommandGroup;"
    $lines += "import edu.wpi.first.wpilibj2.command.ParallelRaceGroup;"
    $lines += "import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;"
    $lines += "import edu.wpi.first.wpilibj2.command.button.CommandXboxController;"
    $lines += "import frc.powerlib.PowerRobotContainer;"
    $lines += "import frc.robot.subsystems.StateMachine;"
    $lines += ""
    $lines += "public final class PowerButtonBindings {"
    $lines += "  private PowerButtonBindings() {}"
    $lines += ""
    $lines += "  public static void configure("
    $lines += "      CommandXboxController driverController,"
    $lines += "      CommandXboxController operatorController,"
    $lines += "      StateMachine stateMachine) {"

    $bindingIndex = 0
    foreach ($binding in @($Bindings)) {
        $commands = @(Get-JsonPropertyValue $binding "commands" @())
        if ($commands.Count -eq 0) {
            continue
        }

        $bindingName = (Get-JsonPropertyValue $binding "name" "binding").ToString()
        $bindingIdProperty = Get-JsonPropertyValue $binding "id"
        $bindingId = if (-not [string]::IsNullOrWhiteSpace($bindingIdProperty)) {
            $bindingIdProperty.ToString()
        } else {
            $bindingName
        }
        $commandOwner = Convert-ToJavaIdentifier $bindingId 'binding'
        $variableName = "$($commandOwner)Command$bindingIndex"
        $controller = (Get-JsonPropertyValue $binding "controller" "driver").ToString()
        $input = (Get-JsonPropertyValue $binding "input" "a").ToString()
        $event = (Get-JsonPropertyValue $binding "event" "onTrue").ToString()
        $triggerExpression = Get-BindingTriggerExpression $controller $input
        $eventName = Get-BindingEventName $event
        $commandVariableDefaults = @($commands | ForEach-Object { Get-BindingCommandVariableDefaultLines $_ $Subsystems $commandOwner } | Select-Object -Unique)
        $commandExpressions = @($commands | ForEach-Object { New-BindingCommandExpression $_ $Subsystems $commandOwner })
        $allInstantFunctions = @($commands | Where-Object { (Get-BindingCommandKind $_) -eq "function" }).Count -eq $commands.Count
        $commandExpression = if ($allInstantFunctions) {
            New-InstantBindingGroupExpression $commands $Subsystems $commandOwner
        } elseif ($commandExpressions.Count -eq 1) {
            $commandExpressions[0]
        } else {
            "new SequentialCommandGroup($($commandExpressions -join ', '))"
        }

        $lines += ""
        foreach ($defaultLine in $commandVariableDefaults) {
            $lines += $defaultLine
        }
        $lines += "    Command $variableName = $commandExpression;"
        $lines += "    $triggerExpression.$eventName($variableName);"
        $bindingIndex++
    }

    $lines += "  }"
    $lines += "}"

    Set-Content -Path $outputFile -Value ($lines -join "`n") -Encoding ascii
    return $outputFile
}

function Update-BindingsFromJson {
    param(
        [Parameter(Mandatory = $true)][string]$BindingJsonPath,
        [Parameter(Mandatory = $true)][string]$SubsystemJsonPath
    )

    $subsystemDocument = Read-SubsystemDocument $SubsystemJsonPath
    $bindingDocument = Read-BindingDocument $BindingJsonPath
    $subsystems = @($subsystemDocument.subsystems)
    $bindings = @($bindingDocument.bindings)

    $constantsBySubsystemId = @{}
    foreach ($subsystem in $subsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $constantsBySubsystemId[$metadata.Id] = @()
    }

    $collectConstants = {
        param($Command)

        $kind = Get-BindingCommandKind $Command
        if ($kind -ne "function") {
            if ($kind -eq "wait") {
                $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
                $subsystem = Find-SubsystemById $subsystems $subsystemId
                $constantProperty = Get-JsonPropertyValue $Command "constantName"
                if ([string]::IsNullOrWhiteSpace($constantProperty)) {
                    throw "Wait command needs a constant name."
                }
                $value = Get-JsonPropertyValue $Command "value"
                if ($null -eq $value) {
                    throw "Wait command needs a value."
                }

                $metadata = Get-SubsystemMetadata $subsystem
                $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
                $constantsBySubsystemId[$metadata.Id] += "  public static final double $constantName = $(Format-JavaDoubleLiteral $value);"
                return
            }
            foreach ($child in @(Get-JsonPropertyValue $Command "children" @())) {
                & $collectConstants $child
            }
            return
        }

        $subsystemId = (Get-JsonPropertyValue $Command "subsystemId" "").ToString()
        $method = (Get-JsonPropertyValue $Command "method" "").ToString()
        $subsystem = Find-SubsystemById $subsystems $subsystemId
        if (-not (Get-BindingMethodNeedsValue $subsystem $method)) {
            return
        }
        $constantProperty = Get-JsonPropertyValue $Command "constantName"
        if ([string]::IsNullOrWhiteSpace($constantProperty)) {
            throw "Binding command '$method' for subsystem '$($subsystem.name)' needs a constant name."
        }
        $value = Get-JsonPropertyValue $Command "value"
        if ($null -eq $value) {
            throw "Binding command '$method' for subsystem '$($subsystem.name)' needs a value."
        }

        $metadata = Get-SubsystemMetadata $subsystem
        $constantName = Convert-ToJavaConstantName $constantProperty.ToString()
        $constantsBySubsystemId[$metadata.Id] += "  public static final double $constantName = $(Format-JavaDoubleLiteral $value);"
    }

    foreach ($binding in $bindings) {
        foreach ($command in @(Get-JsonPropertyValue $binding "commands" @())) {
            & $collectConstants $command
        }
    }

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    foreach ($subsystem in $subsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $constantsFile = Join-Path $constantsDir "$($metadata.PascalName)Constants.java"
        if (-not (Test-Path $constantsFile)) {
            throw "Missing $constantsFile. Run subsystem update before binding update."
        }
        Rewrite-BindingConstantsBlock $constantsFile @($constantsBySubsystemId[$metadata.Id] | Select-Object -Unique)
    }

    $written = Write-PowerButtonBindingsFile $bindings $subsystems
    Save-BindingDocument $BindingJsonPath $bindingDocument
    Write-Host "Generated $written"
    Write-Host "Updated PowerButtonBindings.java and binding constants from $BindingJsonPath"
}

function Update-SubsystemsFromJson {
    param([Parameter(Mandatory = $true)][string]$JsonPath)

    $document = Read-SubsystemDocument $JsonPath
    $subsystems = @($document.subsystems)

    $constantsBarrel = Join-Path (Get-Location) "src/main/java/frc/robot/Constants.java"
    if (-not (Test-Path $constantsBarrel)) {
        throw "Missing src/main/java/frc/robot/Constants.java. Run robotLibraryInstall first."
    }

    $stateMachineFile = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems/StateMachine.java"
    if (-not (Test-Path $stateMachineFile)) {
        throw "Missing src/main/java/frc/robot/subsystems/StateMachine.java. Run robotLibraryInstall first."
    }

    $powerDashboardFile = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems/PowerDashboard.java"
    if (-not (Test-Path $powerDashboardFile)) {
        throw "Missing src/main/java/frc/robot/subsystems/PowerDashboard.java. Run robotLibraryInstall first."
    }

    $written = @()
    $characterizationWritten = @()
    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    $customBlocksById = Get-CustomConstantsBySubsystemId $constantsDir
    $written += Write-SwerveConstantsFile $document.swerve
    foreach ($subsystem in $subsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $written += Write-ConstantsFile $subsystem $metadata $customBlocksById
        $characterizationFile = Write-CharacterizationFile $subsystem $metadata
        if ($null -ne $characterizationFile) {
            $characterizationWritten += $characterizationFile
        }
    }

    Rewrite-ConstantsBlock $constantsBarrel $subsystems
    Rewrite-StateMachineBlock $stateMachineFile $subsystems
    Ensure-PowerDashboardRawNetworkTablesSupport $powerDashboardFile
    Rewrite-PowerDashboardCharacterizationBlock $powerDashboardFile $subsystems
    Remove-DeletedGeneratedFiles $subsystems
    Remove-StaleCharacterizationFiles $subsystems
    Save-SubsystemDocument $JsonPath $document

    foreach ($file in $written) {
        Write-Host "Generated $file"
    }
    foreach ($file in $characterizationWritten) {
        Write-Host "Generated $file"
    }
    Write-Host "Updated Constants.java, StateMachine.java, and PowerDashboard.java from $JsonPath"
}

function Invoke-BuildIfNeeded {
    if ($SkipBuild) {
        return
    }

    $isWindowsHost = [System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT
    $gradlew = if ($isWindowsHost) { ".\gradlew.bat" } else { "./gradlew" }
    if (Test-Path $gradlew) {
        & $gradlew --no-daemon --console=plain build
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    } else {
        Write-Host "Skipped build because no Gradle wrapper was found."
    }
}

if ($UpdateSubsystems -or $UpdateBindings) {
    if ($UpdateSubsystems) {
        Update-SubsystemsFromJson $SubsystemsJson
    }
    if ($UpdateBindings) {
        Update-BindingsFromJson $BindingsJson $SubsystemsJson
    }
    Invoke-BuildIfNeeded
    exit 0
}

Write-Host "PowerLib subsystem generator starting. Answer the prompts below."
Write-Host "Enum prompts show accepted values before the default."

if ((Test-Path $SubsystemsJson) -and (Prompt-Boolean "Update subsystems from ${SubsystemsJson}?" $true)) {
    Update-SubsystemsFromJson $SubsystemsJson
    Invoke-BuildIfNeeded
    exit 0
}

$document = Read-SubsystemDocument $SubsystemsJson

do {
    $subsystem = New-InteractiveSubsystem
    Upsert-SubsystemDocumentEntry $document $subsystem
    Save-SubsystemDocument $SubsystemsJson $document
    Update-SubsystemsFromJson $SubsystemsJson
    $addAnother = Prompt-Boolean "Add another subsystem?" $false
} while ($addAnother)

Invoke-BuildIfNeeded
