param(
    [switch]$SkipBuild,
    [switch]$UpdateSubsystems,
    [string]$SubsystemsJson = "power-tool/generated/powerlib-subsystems.json"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$layoutScript = Join-Path $PSScriptRoot 'project-layout.ps1'
if (-not (Test-Path -LiteralPath $layoutScript)) { $layoutScript = Join-Path $PSScriptRoot 'powerlib-dashboard/scripts/project-layout.ps1' }
. $layoutScript
Set-Location -LiteralPath (Get-PowerLibRobotRoot)
Initialize-PowerToolLayout -RobotRoot (Get-Location).Path
if ($SubsystemsJson -eq 'powerlib-subsystems.json') {
    $SubsystemsJson = 'power-tool/generated/powerlib-subsystems.json'
}

$StateMachineStartMarker = "  // POWERLIB GENERATED SUBSYSTEMS START - DO NOT DELETE"
$StateMachineEndMarker = "  // POWERLIB GENERATED SUBSYSTEMS END - DO NOT DELETE"
$ConstantsStartMarker = "  // POWERLIB GENERATED CONSTANTS START - DO NOT DELETE"
$ConstantsEndMarker = "  // POWERLIB GENERATED CONSTANTS END - DO NOT DELETE"
$CharacterizationStartMarker = "    // POWERLIB GENERATED CHARACTERIZATION START - DO NOT DELETE"
$CharacterizationEndMarker = "    // POWERLIB GENERATED CHARACTERIZATION END - DO NOT DELETE"
$GeneratedFileMarker = "// Generated by PowerLib subsystem tool. Edit power-tool/generated/powerlib-subsystems.json, then run update."
$GeneratedFileMarkerPrefix = "// Generated by PowerLib subsystem tool."
$SubsystemIdMarkerPrefix = "// POWERLIB SUBSYSTEM ID: "
$CustomConstantsStartMarker = "  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE"
$CustomConstantsEndMarker = "  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE"
$BuiltInConstantNames = @("CanBus", "GeneratedTunable", "LED", "Location", "OI", "RobotContainer", "StateMachine", "Swerve", "Tuner", "Vision")

function Prompt-Value {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    $suffix = ""
    if ($null -ne $DefaultValue -and $DefaultValue.Length -gt 0) {
        $suffix = " [$DefaultValue]"
    }

    [Console]::WriteLine()
    [Console]::Write("POWERLIB> $Message$suffix`: ")
    $value = [Console]::ReadLine()
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $DefaultValue
    }

    return $value.Trim()
}

function Prompt-Required {
    param([Parameter(Mandatory = $true)][string]$Message)

    do {
        $value = Prompt-Value $Message
    } while ([string]::IsNullOrWhiteSpace($value))

    return $value.Trim()
}

function Prompt-Enum {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Parameter(Mandatory = $true)][string[]]$AcceptedValues,
        [Parameter(Mandatory = $true)][string]$DefaultValue
    )

    $acceptedText = $AcceptedValues -join ", "
    while ($true) {
        $value = Prompt-Value "$Message (accepted: $acceptedText)" $DefaultValue
        foreach ($accepted in $AcceptedValues) {
            if ($value -ieq $accepted) {
                return $accepted
            }
        }

        Write-Host "Accepted values: $acceptedText"
    }
}

function Prompt-Boolean {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [bool]$DefaultValue = $false
    )

    $defaultText = if ($DefaultValue) { "y" } else { "n" }
    while ($true) {
        $value = (Prompt-Value "$Message (accepted: y, n)" $defaultText).ToLowerInvariant()
        if ($value -eq "y" -or $value -eq "yes" -or $value -eq "true") {
            return $true
        }
        if ($value -eq "n" -or $value -eq "no" -or $value -eq "false") {
            return $false
        }

        Write-Host "Accepted values: y, n"
    }
}

function Prompt-Int {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Nullable[int]]$DefaultValue = $null
    )

    while ($true) {
        $defaultText = if ($null -eq $DefaultValue) { $null } else { $DefaultValue.ToString() }
        $value = Prompt-Value $Message $defaultText
        $parsed = 0
        if ([int]::TryParse($value, [ref]$parsed)) {
            return $parsed
        }

        Write-Host "Please enter a whole number."
    }
}

function Prompt-DoubleText {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    while ($true) {
        $value = Prompt-Value $Message $DefaultValue
        $parsed = 0.0
        if ([double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
            return $value
        }

        Write-Host "Please enter a number."
    }
}

function Prompt-OptionalDoubleText {
    param([Parameter(Mandatory = $true)][string]$Label)

    $value = Prompt-Value "$Label (blank for Optional.empty)" ""
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $null
    }

    $parsed = 0.0
    if (-not [double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        throw "Please enter a number for $Label."
    }

    return $value
}

function Get-JavaIdentifierParts {
    param([Parameter(Mandatory = $true)][string]$Value)

    $splitWords = [regex]::Replace($Value, "([a-z])([A-Z])", '$1 $2')
    return @($splitWords -split "[^A-Za-z0-9]+" | Where-Object { $_.Length -gt 0 })
}

function Assert-NoWhitespaceName {
    param(
        [AllowNull()]$Value,
        [Parameter(Mandatory = $true)][string]$Description
    )

    $rawText = if ($null -eq $Value) { "" } else { $Value.ToString() }
    $text = $rawText.Trim()
    if ([string]::IsNullOrWhiteSpace($text)) {
        throw "$Description is required."
    }
    if ($rawText -match '\s') {
        throw "$Description '$text' cannot contain spaces or other whitespace. Use a single token like IntakeRoller or TestOff."
    }
}

function Convert-ToPascalCase {
    param([Parameter(Mandatory = $true)][string]$Value)

    $parts = @(Get-JavaIdentifierParts $Value)
    if ($parts.Count -eq 0) {
        throw "Subsystem name must contain at least one letter or number."
    }

    return ($parts | ForEach-Object {
        $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1)
    }) -join ""
}

function Convert-ToCamelCase {
    param([Parameter(Mandatory = $true)][string]$Pascal)
    return $Pascal.Substring(0, 1).ToLowerInvariant() + $Pascal.Substring(1)
}

function Convert-ToConstantPrefix {
    param([Parameter(Mandatory = $true)][string]$RawName)
    return (@(Get-JavaIdentifierParts $RawName) | ForEach-Object { $_.ToUpperInvariant() }) -join "_"
}

function Get-StableSubsystemId {
    param([Parameter(Mandatory = $true)]$Subsystem)

    if (($Subsystem.PSObject.Properties.Name -contains "id") -and -not [string]::IsNullOrWhiteSpace($Subsystem.id)) {
        return $Subsystem.id.ToString()
    }

    return Convert-ToCamelCase (Convert-ToPascalCase $Subsystem.name)
}

function Get-SubsystemMetadata {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $pascal = Convert-ToPascalCase $Subsystem.name
    $type = $Subsystem.type.ToString().ToLowerInvariant()
    if ($type -eq "position") {
        $type = "absoluteposition"
    }
    if ($type -ne "velocity" -and $type -ne "velocitytorque" -and $type -ne "absoluteposition" -and $type -ne "relativeposition") {
        throw "Unsupported subsystem type '$($Subsystem.type)' for '$($Subsystem.name)'. Accepted values: velocity, velocityTorque, absolutePosition, relativePosition."
    }

    $subsystemClassName = switch ($type) {
        "velocity" { "VelocitySubsystem" }
        "velocitytorque" { "VelocityTorqueSubsystem" }
        "absoluteposition" { "AbsolutePositionSubsystem" }
        "relativeposition" { "RelativePositionSubsystem" }
    }

    return [pscustomobject]@{
        Id = Get-StableSubsystemId $Subsystem
        Name = $Subsystem.name
        Type = $type
        PascalName = $pascal
        CamelName = Convert-ToCamelCase $pascal
        ConstantPrefix = Convert-ToConstantPrefix $Subsystem.name
        SubsystemClassName = $subsystemClassName
        ConfigConstantName = "$(Convert-ToConstantPrefix $Subsystem.name)_CONFIG"
    }
}

function Get-NeutralModeExpression {
    param([Parameter(Mandatory = $true)][string]$Value)

    if ($Value -ieq "Coast") {
        return "NeutralModeValue.Coast"
    }
    if ($Value -ieq "Brake") {
        return "NeutralModeValue.Brake"
    }

    throw "Unsupported neutral mode '$Value'. Accepted values: Brake, Coast."
}

function Get-OptionalDoubleExpression {
    param($Value)

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace($Value.ToString())) {
        return "Optional.empty()"
    }

    $text = $Value.ToString()
    if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
        $text = "$text.0"
    }

    return "Optional.of($text)"
}

function Get-FocEnabledExpression {
    param($Subsystem)

    if ($Subsystem.PSObject.Properties.Name -contains "focEnabled" -and $null -ne $Subsystem.focEnabled) {
        return $Subsystem.focEnabled.ToString().ToLowerInvariant()
    }

    return "true"
}

function Get-TorqueFeedForwardExpression {
    param($Subsystem)

    if ($Subsystem.PSObject.Properties.Name -contains "torqueFF" -and $null -ne $Subsystem.torqueFF) {
        $text = $Subsystem.torqueFF.ToString()
        if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
            $text = "$text.0"
        }
        return $text
    }

    return "0.0"
}

function Format-IndentedList {
    param(
        [Parameter(Mandatory = $true)][string[]]$Expressions,
        [Parameter(Mandatory = $true)][string]$Indent
    )

    return ($Expressions | ForEach-Object { "$Indent$_" }) -join ",`n"
}

function Convert-MotorsToExpressions {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $motors = @($Subsystem.motors)
    if ($motors.Count -eq 0) {
        throw "Subsystem '$($Subsystem.name)' must have at least one motor."
    }

    $leader = $motors | Where-Object { $_.role -eq "leader" } | Select-Object -First 1
    if ($null -eq $leader) {
        throw "Subsystem '$($Subsystem.name)' must have one leader motor."
    }

    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"
    $leaderReversed = Get-ObjectPropertyValue $leader "reversed" $false
    $lines = @("MotorConfig.leader($($leader.id), $(Get-NeutralModeExpression $leaderNeutralMode), $($leaderReversed.ToString().ToLowerInvariant()))")
    foreach ($follower in ($motors | Where-Object { $_.role -eq "follower" })) {
        $followerNeutralMode = Get-ObjectPropertyValue $follower "neutralMode" $null
        $neutralMode = if ($null -ne $followerNeutralMode -and -not [string]::IsNullOrWhiteSpace($followerNeutralMode.ToString())) {
            $followerNeutralMode
        } else {
            $leaderNeutralMode
        }
        $followerReversed = Get-ObjectPropertyValue $follower "reversed" $false
        $lines += "MotorConfig.follower($($follower.id), $(Get-NeutralModeExpression $neutralMode), $($followerReversed.ToString().ToLowerInvariant()))"
    }

    return $lines
}

function Get-LeaderMotor {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $motors = @($Subsystem.motors)
    if ($motors.Count -eq 0) {
        throw "Subsystem '$($Subsystem.name)' must have at least one motor."
    }

    $leader = $motors | Where-Object { $_.role -eq "leader" } | Select-Object -First 1
    if ($null -eq $leader) {
        throw "Subsystem '$($Subsystem.name)' must have one leader motor."
    }

    return $leader
}

function Convert-MotorsToConstantDeclarations {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $leader = Get-LeaderMotor $Subsystem
    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"
    $leaderReversed = Get-ObjectPropertyValue $leader "reversed" $false
    $lines = @(
        "  public static final int LEADER_MOTOR_ID = $($leader.id);",
        "  public static final NeutralModeValue LEADER_NEUTRAL_MODE = $(Get-NeutralModeExpression $leaderNeutralMode);",
        "  public static final boolean LEADER_REVERSED = $($leaderReversed.ToString().ToLowerInvariant());"
    )

    $index = 1
    foreach ($follower in (@($Subsystem.motors) | Where-Object { $_.role -eq "follower" })) {
        $followerNeutralMode = Get-ObjectPropertyValue $follower "neutralMode" $null
        $neutralModeExpression = if ($null -ne $followerNeutralMode -and -not [string]::IsNullOrWhiteSpace($followerNeutralMode.ToString())) {
            Get-NeutralModeExpression $followerNeutralMode
        } else {
            "LEADER_NEUTRAL_MODE"
        }
        $followerReversed = Get-ObjectPropertyValue $follower "reversed" $false
        $lines += "  public static final int FOLLOWER_${index}_MOTOR_ID = $($follower.id);"
        $lines += "  public static final NeutralModeValue FOLLOWER_${index}_NEUTRAL_MODE = $neutralModeExpression;"
        $lines += "  public static final boolean FOLLOWER_${index}_REVERSED = $($followerReversed.ToString().ToLowerInvariant());"
        $index++
    }

    return $lines -join "`n"
}

function Convert-MotorsToConstantExpressions {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $null = Get-LeaderMotor $Subsystem
    $lines = @("MotorConfig.leader(LEADER_MOTOR_ID, LEADER_NEUTRAL_MODE, LEADER_REVERSED)")

    $index = 1
    foreach ($follower in (@($Subsystem.motors) | Where-Object { $_.role -eq "follower" })) {
        $lines += "MotorConfig.follower(FOLLOWER_${index}_MOTOR_ID, FOLLOWER_${index}_NEUTRAL_MODE, FOLLOWER_${index}_REVERSED)"
        $index++
    }

    return $lines
}

function New-InteractiveMotors {
    $leaderId = Prompt-Int "Leader motor CAN ID"
    $neutral = Prompt-Enum "Leader neutral mode" @("Brake", "Coast") "Brake"
    $leaderReversed = Prompt-Boolean "Leader reversed?" $false

    $motors = @(
        [pscustomobject]@{
            role = "leader"
            id = $leaderId
            neutralMode = $neutral
            reversed = $leaderReversed
        }
    )

    $followerIds = Prompt-Value "Follower motor CAN IDs, comma-separated (blank for none)" ""
    foreach ($idText in ($followerIds -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_.Length -gt 0 })) {
        $followerId = [int]$idText
        $motors += [pscustomobject]@{
            role = "follower"
            id = $followerId
            reversed = Prompt-Boolean "Follower $followerId reversed?" $false
        }
    }

    return $motors
}

function New-InteractivePidConfig {
    if (-not (Prompt-Boolean "Configure PID/feedforward values?" $false)) {
        return [ordered]@{
            kP = "0.0"
            kI = "0.0"
            kD = "0.0"
            kG = "0.0"
            kS = $null
            kV = $null
            kA = $null
        }
    }

    return [ordered]@{
        kP = Prompt-DoubleText "kP" "0.0"
        kI = Prompt-DoubleText "kI" "0.0"
        kD = Prompt-DoubleText "kD" "0.0"
        kG = Prompt-DoubleText "kG" "0.0"
        kS = Prompt-OptionalDoubleText "kS"
        kV = Prompt-OptionalDoubleText "kV"
        kA = Prompt-OptionalDoubleText "kA"
    }
}

function New-InteractiveSubsystem {
    $rawName = Prompt-Required "Subsystem name, example shooter"
    Assert-NoWhitespaceName $rawName "Subsystem name"
    $type = (Prompt-Enum "Subsystem type" @("velocity", "velocityTorque", "absolutePosition", "relativePosition") "velocity").ToLowerInvariant()
    $canonicalType = switch ($type) {
        "velocitytorque" { "velocityTorque" }
        "absoluteposition" { "absolutePosition" }
        "relativeposition" { "relativePosition" }
        default { $type }
    }
    $stableId = Convert-ToCamelCase (Convert-ToPascalCase $rawName)

    $subsystem = [ordered]@{
        id = $stableId
        name = $rawName
        type = $canonicalType
        motors = @(New-InteractiveMotors)
        pid = New-InteractivePidConfig
        focEnabled = Prompt-Boolean "Enable FOC?" $true
        torqueFF = if ($type -eq "velocitytorque") { Prompt-DoubleText "Torque FF" "0.0" } else { "0.0" }
        ratios = [ordered]@{
            sensorToMechanism = Prompt-DoubleText "Sensor-to-mechanism ratio" "1.0"
            rotorToSensor = Prompt-DoubleText "Rotor-to-sensor ratio" "1.0"
        }
        motionMagic = [ordered]@{}
    }

    if ($type -eq "absoluteposition") {
        $subsystem.cancoder = [ordered]@{
            id = Prompt-Int "CANcoder CAN ID"
            magnetOffset = Prompt-DoubleText "CANcoder magnet offset rotations" "0.0"
            discontinuityPoint = Prompt-DoubleText "CANcoder discontinuity point rotations" "0.5"
        }
        $subsystem.motionMagic.cruiseVelocity = Prompt-DoubleText "Motion Magic cruise velocity" "0.0"
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
        $subsystem.absolutePosition = [ordered]@{
            units = Prompt-Value "Position units" "rotations"
            default = Prompt-OptionalDoubleText "Default position"
        }
    } elseif ($type -eq "relativeposition") {
        $subsystem.motionMagic.cruiseVelocity = Prompt-DoubleText "Motion Magic cruise velocity" "0.0"
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
        $subsystem.slowMotionMagic = [ordered]@{
            cruiseVelocity = Prompt-DoubleText "Slow Motion Magic cruise velocity" "0.0"
            acceleration = Prompt-DoubleText "Slow Motion Magic acceleration" "0.0"
        }
        $subsystem.relativePosition = [ordered]@{
            units = Prompt-Value "Position units" "rotations"
            homePosition = Prompt-DoubleText "Home position" "0.0"
            forwardSoftLimit = Prompt-DoubleText "Forward soft limit" "0.0"
            reverseSoftLimit = Prompt-DoubleText "Reverse soft limit" "0.0"
            slowThreshold = Prompt-DoubleText "Slow threshold" "0.0"
            tolerance = Prompt-DoubleText "Position tolerance" "0.05"
            stopVoltage = Prompt-DoubleText "Stop voltage" "0.0"
        }
    } else {
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
    }

    return [pscustomobject]$subsystem
}

function New-DefaultSwerveConfig {
    return [pscustomobject]@{
        driver = [pscustomobject]@{
            maxSpeedCoefficient = 0.75
            velocityScale = 0.95
            maxAngularRateRadiansPerSecond = 9.42477796076938
            joystickDeadband = 0.1
            skewCompensation = -0.03
        }
        requests = [pscustomobject]@{
            maxAngularRateRadiansPerSecond = 4.71238898038469
            translationDeadbandMetersPerSecond = 0.572
            rotationalDeadbandRadiansPerSecond = 0.471238898038469
        }
        driveToPoint = [pscustomobject]@{
            maxAngularRateRadiansPerSecond = 3.141592653589793
            maxSpeedCoefficient = 0.75
            slowSpeedCoefficient = 0.1875
            staticFrictionConstant = 0.085
        }
        heading = [pscustomobject]@{
            kP = 7.0
            kI = 0.0
            kD = 0.0
        }
    }
}

function Test-IsJsonObject {
    param([AllowNull()]$Value)

    return $null -ne $Value -and
        $Value -isnot [array] -and
        $Value -is [System.Management.Automation.PSCustomObject]
}

function Get-ObjectProperty {
    param(
        [AllowNull()]$Object,
        [Parameter(Mandatory = $true)][string]$Name
    )

    if ($null -eq $Object) {
        return $null
    }

    return $Object.PSObject.Properties[$Name]
}

function Get-ObjectPropertyValue {
    param(
        [AllowNull()]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $DefaultValue = $null
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or $null -eq $property.Value) {
        return $DefaultValue
    }

    return $property.Value
}

function Set-ObjectProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $Value
    )

    $Object | Add-Member -MemberType NoteProperty -Name $Name -Value $Value -Force
}

function Ensure-ObjectProperty {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name,
        $DefaultValue
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or $null -eq $property.Value) {
        Set-ObjectProperty $Object $Name $DefaultValue
    }
}

function Ensure-ObjectPropertyObject {
    param(
        [Parameter(Mandatory = $true)]$Object,
        [Parameter(Mandatory = $true)][string]$Name
    )

    $property = Get-ObjectProperty $Object $Name
    if ($null -eq $property -or -not (Test-IsJsonObject $property.Value)) {
        Set-ObjectProperty $Object $Name ([pscustomobject]@{})
    }
}

function Ensure-SwerveConfig {
    param([Parameter(Mandatory = $true)]$Document)

    $defaults = New-DefaultSwerveConfig
    Ensure-ObjectPropertyObject $Document "swerve"
    Ensure-ObjectPropertyObject $Document.swerve "driver"
    Ensure-ObjectPropertyObject $Document.swerve "requests"
    Ensure-ObjectPropertyObject $Document.swerve "driveToPoint"
    Ensure-ObjectPropertyObject $Document.swerve "heading"

    Ensure-ObjectProperty $Document.swerve.driver "maxSpeedCoefficient" $defaults.driver.maxSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driver "velocityScale" $defaults.driver.velocityScale
    Ensure-ObjectProperty $Document.swerve.driver "maxAngularRateRadiansPerSecond" $defaults.driver.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.driver "joystickDeadband" $defaults.driver.joystickDeadband
    Ensure-ObjectProperty $Document.swerve.driver "skewCompensation" $defaults.driver.skewCompensation

    Ensure-ObjectProperty $Document.swerve.requests "maxAngularRateRadiansPerSecond" $defaults.requests.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.requests "translationDeadbandMetersPerSecond" $defaults.requests.translationDeadbandMetersPerSecond
    Ensure-ObjectProperty $Document.swerve.requests "rotationalDeadbandRadiansPerSecond" $defaults.requests.rotationalDeadbandRadiansPerSecond

    Ensure-ObjectProperty $Document.swerve.driveToPoint "maxAngularRateRadiansPerSecond" $defaults.driveToPoint.maxAngularRateRadiansPerSecond
    Ensure-ObjectProperty $Document.swerve.driveToPoint "maxSpeedCoefficient" $defaults.driveToPoint.maxSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driveToPoint "slowSpeedCoefficient" $defaults.driveToPoint.slowSpeedCoefficient
    Ensure-ObjectProperty $Document.swerve.driveToPoint "staticFrictionConstant" $defaults.driveToPoint.staticFrictionConstant

    Ensure-ObjectProperty $Document.swerve.heading "kP" $defaults.heading.kP
    Ensure-ObjectProperty $Document.swerve.heading "kI" $defaults.heading.kI
    Ensure-ObjectProperty $Document.swerve.heading "kD" $defaults.heading.kD

    return $Document.swerve
}

function Normalize-SubsystemConfig {
    param([Parameter(Mandatory = $true)]$Subsystem)

    Assert-NoWhitespaceName (Get-ObjectPropertyValue $Subsystem "name" "") "Subsystem name"
    if ($BuiltInConstantNames -contains (Convert-ToPascalCase $Subsystem.name)) {
        throw "Subsystem name '$($Subsystem.name)' is reserved for robot constants."
    }
    Ensure-ObjectProperty $Subsystem "id" (Get-StableSubsystemId $Subsystem)
    Ensure-ObjectProperty $Subsystem "motors" (@())

    $motors = @($Subsystem.motors)
    for ($index = 0; $index -lt $motors.Count; $index++) {
        $motor = $motors[$index]
        if (-not (Test-IsJsonObject $motor)) {
            continue
        }

        $defaultRole = if ($index -eq 0) { "leader" } else { "follower" }
        Ensure-ObjectProperty $motor "role" $defaultRole
        Ensure-ObjectProperty $motor "reversed" $false
    }

    $leader = $motors |
        Where-Object { (Get-ObjectPropertyValue $_ "role" "").ToString() -ieq "leader" } |
        Select-Object -First 1
    $leaderNeutralMode = Get-ObjectPropertyValue $leader "neutralMode" "Brake"

    foreach ($motor in $motors) {
        if (-not (Test-IsJsonObject $motor)) {
            continue
        }

        $role = (Get-ObjectPropertyValue $motor "role" "").ToString()
        $defaultNeutralMode = if ($role -ieq "follower") { $leaderNeutralMode } else { "Brake" }
        Ensure-ObjectProperty $motor "neutralMode" $defaultNeutralMode
    }
    $Subsystem.motors = @($motors)

    Ensure-ObjectPropertyObject $Subsystem "pid"
    Ensure-ObjectProperty $Subsystem.pid "kP" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kI" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kD" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kG" "0.0"
    Ensure-ObjectProperty $Subsystem.pid "kS" $null
    Ensure-ObjectProperty $Subsystem.pid "kV" $null
    Ensure-ObjectProperty $Subsystem.pid "kA" $null

    Ensure-ObjectPropertyObject $Subsystem "ratios"
    Ensure-ObjectProperty $Subsystem.ratios "sensorToMechanism" "1.0"
    Ensure-ObjectProperty $Subsystem.ratios "rotorToSensor" "1.0"

    Ensure-ObjectPropertyObject $Subsystem "motionMagic"
    Ensure-ObjectProperty $Subsystem.motionMagic "cruiseVelocity" "0.0"
    Ensure-ObjectProperty $Subsystem.motionMagic "acceleration" "0.0"
    Ensure-ObjectProperty $Subsystem "focEnabled" $true
    Ensure-ObjectProperty $Subsystem "torqueFF" "0.0"

    $type = (Get-ObjectPropertyValue $Subsystem "type" "").ToString().ToLowerInvariant()
    if ($type -eq "position") {
        Set-ObjectProperty $Subsystem "type" "absolutePosition"
        $type = "absoluteposition"
    }

    if ($type -eq "absoluteposition") {
        $absolutePositionConfig = Get-ObjectPropertyValue $Subsystem "absolutePosition" $null
        if (-not (Test-IsJsonObject $absolutePositionConfig)) {
            $positionConfig = Get-ObjectPropertyValue $Subsystem "position" $null
            if (Test-IsJsonObject $positionConfig) {
                Set-ObjectProperty $Subsystem "absolutePosition" $positionConfig
            } else {
                Set-ObjectProperty $Subsystem "absolutePosition" ([pscustomobject]@{})
            }
        }
        Ensure-ObjectProperty $Subsystem.absolutePosition "units" "rotations"
        Ensure-ObjectProperty $Subsystem.absolutePosition "default" $null

        $cancoderConfig = Get-ObjectPropertyValue $Subsystem "cancoder" $null
        if (Test-IsJsonObject $cancoderConfig) {
            Ensure-ObjectProperty $Subsystem.cancoder "magnetOffset" "0.0"
            Ensure-ObjectProperty $Subsystem.cancoder "discontinuityPoint" "0.5"
        }
    } elseif ($type -eq "relativeposition") {
        Ensure-ObjectPropertyObject $Subsystem "slowMotionMagic"
        Ensure-ObjectProperty $Subsystem.slowMotionMagic "cruiseVelocity" "0.0"
        Ensure-ObjectProperty $Subsystem.slowMotionMagic "acceleration" "0.0"

        $relativePositionConfig = Get-ObjectPropertyValue $Subsystem "relativePosition" $null
        if (-not (Test-IsJsonObject $relativePositionConfig)) {
            $positionConfig = Get-ObjectPropertyValue $Subsystem "position" $null
            if (Test-IsJsonObject $positionConfig) {
                Set-ObjectProperty $Subsystem "relativePosition" $positionConfig
            } else {
                Set-ObjectProperty $Subsystem "relativePosition" ([pscustomobject]@{})
            }
        }
        Ensure-ObjectProperty $Subsystem.relativePosition "units" "rotations"
        Ensure-ObjectProperty $Subsystem.relativePosition "homePosition" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "forwardSoftLimit" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "reverseSoftLimit" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "slowThreshold" "0.0"
        Ensure-ObjectProperty $Subsystem.relativePosition "tolerance" "0.05"
        Ensure-ObjectProperty $Subsystem.relativePosition "stopVoltage" "0.0"
    }
}

function Read-SubsystemDocument {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return [pscustomobject]@{
            swerve = New-DefaultSwerveConfig
            subsystems = @()
        }
    }

    $document = Get-Content -Path $Path -Raw | ConvertFrom-Json
    if (-not (Test-IsJsonObject $document)) {
        $document = [pscustomobject]@{}
    }
    Ensure-ObjectProperty $document "subsystems" (@())
    Ensure-SwerveConfig $document | Out-Null

    $document.subsystems = @($document.subsystems)
    foreach ($subsystem in @($document.subsystems)) {
        if (Test-IsJsonObject $subsystem) {
            Normalize-SubsystemConfig $subsystem
        }
    }
    return $document
}

function Save-SubsystemDocument {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Document
    )

    Ensure-SwerveConfig $Document | Out-Null
    $Document.subsystems = @($Document.subsystems | Sort-Object { (Get-SubsystemMetadata $_).PascalName })
    $parent = Split-Path -Parent ([System.IO.Path]::GetFullPath($Path))
    New-Item -ItemType Directory -Force -Path $parent | Out-Null
    $Document | ConvertTo-Json -Depth 12 | Set-Content -Path $Path -Encoding ascii
}

function Get-SwerveConfigValue {
    param(
        [Parameter(Mandatory = $true)]$SwerveConfig,
        [Parameter(Mandatory = $true)][string[]]$Path,
        [Parameter(Mandatory = $true)]$DefaultValue
    )

    $current = $SwerveConfig
    foreach ($segment in $Path) {
        $property = Get-ObjectProperty $current $segment
        if ($null -eq $property) {
            return $DefaultValue
        }
        $current = $property.Value
    }

    if ($null -eq $current) {
        return $DefaultValue
    }

    return $current
}

function New-SwerveConstantsContent {
    param([Parameter(Mandatory = $true)]$SwerveConfig)

    $defaults = New-DefaultSwerveConfig
    $driverMaxSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driver", "maxSpeedCoefficient") $defaults.driver.maxSpeedCoefficient
    $driverVelocityScale =
        Get-SwerveConfigValue $SwerveConfig @("driver", "velocityScale") $defaults.driver.velocityScale
    $driverMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("driver", "maxAngularRateRadiansPerSecond") $defaults.driver.maxAngularRateRadiansPerSecond
    $driverJoystickDeadband =
        Get-SwerveConfigValue $SwerveConfig @("driver", "joystickDeadband") $defaults.driver.joystickDeadband
    $driverSkewCompensation =
        Get-SwerveConfigValue $SwerveConfig @("driver", "skewCompensation") $defaults.driver.skewCompensation

    $requestMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("requests", "maxAngularRateRadiansPerSecond") $defaults.requests.maxAngularRateRadiansPerSecond
    $requestTranslationDeadband =
        Get-SwerveConfigValue $SwerveConfig @("requests", "translationDeadbandMetersPerSecond") $defaults.requests.translationDeadbandMetersPerSecond
    $requestRotationalDeadband =
        Get-SwerveConfigValue $SwerveConfig @("requests", "rotationalDeadbandRadiansPerSecond") $defaults.requests.rotationalDeadbandRadiansPerSecond

    $driveToPointMaxAngularRate =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "maxAngularRateRadiansPerSecond") $defaults.driveToPoint.maxAngularRateRadiansPerSecond
    $driveToPointMaxSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "maxSpeedCoefficient") $defaults.driveToPoint.maxSpeedCoefficient
    $driveToPointSlowSpeedCoefficient =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "slowSpeedCoefficient") $defaults.driveToPoint.slowSpeedCoefficient
    $driveToPointStaticFrictionConstant =
        Get-SwerveConfigValue $SwerveConfig @("driveToPoint", "staticFrictionConstant") $defaults.driveToPoint.staticFrictionConstant

    $headingKP = Get-SwerveConfigValue $SwerveConfig @("heading", "kP") $defaults.heading.kP
    $headingKI = Get-SwerveConfigValue $SwerveConfig @("heading", "kI") $defaults.heading.kI
    $headingKD = Get-SwerveConfigValue $SwerveConfig @("heading", "kD") $defaults.heading.kD

    return @"
package frc.robot.constants;

/**
 * PowerLib-owned swerve behavior constants.
 *
 * <p>Phoenix/Tuner X hardware constants stay in {@link TunerConstants}; these values are the driver
 * feel and heading-control defaults that Power Tool can live-tune and then save back to
 * power-tool/generated/powerlib-subsystems.json.
 */
public class SwerveConstants {
  public static final double DRIVER_MAX_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driverMaxSpeedCoefficient);
  public static final double DRIVER_VELOCITY_SCALE = $(Format-JavaDoubleLiteral $driverVelocityScale);
  public static final double DRIVER_MAX_ANGULAR_RATE_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $driverMaxAngularRate);
  public static final double DRIVER_JOYSTICK_DEADBAND = $(Format-JavaDoubleLiteral $driverJoystickDeadband);
  public static final double DRIVER_SKEW_COMPENSATION = $(Format-JavaDoubleLiteral $driverSkewCompensation);

  public static final double REQUEST_MAX_ANGULAR_RATE_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $requestMaxAngularRate);
  public static final double REQUEST_TRANSLATION_DEADBAND_METERS_PER_SECOND = $(Format-JavaDoubleLiteral $requestTranslationDeadband);
  public static final double REQUEST_ROTATIONAL_DEADBAND_RADIANS_PER_SECOND = $(Format-JavaDoubleLiteral $requestRotationalDeadband);

  public static final double DRIVE_TO_POINT_MAX_ANGULAR_RATE_RADIANS_PER_SECOND =
      $(Format-JavaDoubleLiteral $driveToPointMaxAngularRate);
  public static final double DRIVE_TO_POINT_MAX_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driveToPointMaxSpeedCoefficient);
  public static final double DRIVE_TO_POINT_SLOW_SPEED_COEFFICIENT = $(Format-JavaDoubleLiteral $driveToPointSlowSpeedCoefficient);
  public static final double DRIVE_TO_POINT_STATIC_FRICTION_CONSTANT = $(Format-JavaDoubleLiteral $driveToPointStaticFrictionConstant);

  public static final double HEADING_KP = $(Format-JavaDoubleLiteral $headingKP);
  public static final double HEADING_KI = $(Format-JavaDoubleLiteral $headingKI);
  public static final double HEADING_KD = $(Format-JavaDoubleLiteral $headingKD);

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function Upsert-SubsystemDocumentEntry {
    param(
        [Parameter(Mandatory = $true)]$Document,
        [Parameter(Mandatory = $true)]$Subsystem
    )

    $metadata = Get-SubsystemMetadata $Subsystem
    $Document.subsystems = @($Document.subsystems | Where-Object { (Get-SubsystemMetadata $_).Id -ne $metadata.Id })
    $Document.subsystems += $Subsystem
}

function New-VelocityConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final double TORQUE_FF = $(Get-TorqueFeedForwardExpression $Subsystem);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";

  public static final VelocitySubsystemConfig $($Metadata.ConfigConstantName) =
      new VelocitySubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          TORQUE_FF);

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function New-AbsolutePositionConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "
    $absolutePositionConfig = if (($Subsystem.PSObject.Properties.Name -contains "absolutePosition") -and $null -ne $Subsystem.absolutePosition) {
        $Subsystem.absolutePosition
    } else {
        $Subsystem.position
    }

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.AbsolutePositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final int CANCODER_ID = $($Subsystem.cancoder.id);
  public static final double CANCODER_MAGNET_OFFSET = $($Subsystem.cancoder.magnetOffset);
  public static final double CANCODER_DISCONTINUITY_POINT = $($Subsystem.cancoder.discontinuityPoint);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";
  public static final String POSITION_UNITS = "$($absolutePositionConfig.units)";
  public static final Optional<Double> DEFAULT_POSITION = $(Get-OptionalDoubleExpression $absolutePositionConfig.default);

  public static final AbsolutePositionSubsystemConfig $($Metadata.ConfigConstantName) =
      new AbsolutePositionSubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new CancoderConfig(CANCODER_ID, CANCODER_MAGNET_OFFSET, CANCODER_DISCONTINUITY_POINT),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          DEFAULT_POSITION);

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function New-RelativePositionConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorConstants = Convert-MotorsToConstantDeclarations $Subsystem
    $motorList = Format-IndentedList (Convert-MotorsToConstantExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.RelativePositionSubsystemConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
$motorConstants
  public static final double KP = $($Subsystem.pid.kP);
  public static final double KI = $($Subsystem.pid.kI);
  public static final double KD = $($Subsystem.pid.kD);
  public static final double KG = $($Subsystem.pid.kG);
  public static final Optional<Double> KS = $(Get-OptionalDoubleExpression $Subsystem.pid.kS);
  public static final Optional<Double> KV = $(Get-OptionalDoubleExpression $Subsystem.pid.kV);
  public static final Optional<Double> KA = $(Get-OptionalDoubleExpression $Subsystem.pid.kA);
  public static final double SENSOR_TO_MECHANISM_RATIO = $($Subsystem.ratios.sensorToMechanism);
  public static final double ROTOR_TO_SENSOR_RATIO = $($Subsystem.ratios.rotorToSensor);
  public static final boolean FOC_ENABLED = $(Get-FocEnabledExpression $Subsystem);
  public static final double MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.motionMagic.cruiseVelocity);
  public static final double MOTION_MAGIC_ACCELERATION = $($Subsystem.motionMagic.acceleration);
  public static final double SLOW_MOTION_MAGIC_CRUISE_VELOCITY = $($Subsystem.slowMotionMagic.cruiseVelocity);
  public static final double SLOW_MOTION_MAGIC_ACCELERATION = $($Subsystem.slowMotionMagic.acceleration);
  public static final String NAME = "$($Metadata.PascalName)";
  public static final String POSITION_UNITS = "$($Subsystem.relativePosition.units)";
  public static final double HOME_POSITION = $($Subsystem.relativePosition.homePosition);
  public static final double FORWARD_SOFT_LIMIT = $($Subsystem.relativePosition.forwardSoftLimit);
  public static final double REVERSE_SOFT_LIMIT = $($Subsystem.relativePosition.reverseSoftLimit);
  public static final double SLOW_THRESHOLD = $($Subsystem.relativePosition.slowThreshold);
  public static final double POSITION_TOLERANCE = $($Subsystem.relativePosition.tolerance);
  public static final double STOP_VOLTAGE = $($Subsystem.relativePosition.stopVoltage);

  public static final RelativePositionSubsystemConfig $($Metadata.ConfigConstantName) =
      new RelativePositionSubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              KP,
              KI,
              KD,
              KG,
              KS,
              KV,
              KA,
              SENSOR_TO_MECHANISM_RATIO,
              ROTOR_TO_SENSOR_RATIO,
              FOC_ENABLED),
          new MotionMagicConfig(MOTION_MAGIC_CRUISE_VELOCITY, MOTION_MAGIC_ACCELERATION),
          new MotionMagicConfig(SLOW_MOTION_MAGIC_CRUISE_VELOCITY, SLOW_MOTION_MAGIC_ACCELERATION),
          NAME,
          POSITION_UNITS,
          HOME_POSITION,
          FORWARD_SOFT_LIMIT,
          REVERSE_SOFT_LIMIT,
          SLOW_THRESHOLD,
          POSITION_TOLERANCE,
          STOP_VOLTAGE);

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function Ensure-ConstantsMarkers {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $content = Get-Content -Path $ConstantsPath -Raw
    if ($content.Contains($ConstantsStartMarker) -and $content.Contains($ConstantsEndMarker)) {
        return
    }

    $index = $content.LastIndexOf("}")
    if ($index -lt 0) {
        throw "Could not find closing brace in Constants.java."
    }

    $markers = "$ConstantsStartMarker`n$ConstantsEndMarker`n"
    $updated = $content.Substring(0, $index).TrimEnd() + "`n`n$markers}"
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Remove-UnmarkedGeneratedConstants {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $lines = @(Get-Content -Path $ConstantsPath)
    $kept = @()
    foreach ($line in $lines) {
        $match = [regex]::Match($line, "^\s*public static final class\s+([A-Za-z0-9_]+)\s+extends\s+frc\.robot\.constants\.[A-Za-z0-9_]+Constants\s+\{\}\s*$")
        if ($match.Success -and -not ($BuiltInConstantNames -contains $match.Groups[1].Value)) {
            continue
        }
        $kept += $line
    }

    Set-Content -Path $ConstantsPath -Value ($kept -join "`n") -Encoding ascii
}

function Rewrite-ConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$ConstantsPath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    Ensure-ConstantsMarkers $ConstantsPath
    Remove-UnmarkedGeneratedConstants $ConstantsPath
    Ensure-ConstantsMarkers $ConstantsPath

    $content = Get-Content -Path $ConstantsPath -Raw
    $start = $content.IndexOf($ConstantsStartMarker) + $ConstantsStartMarker.Length
    $end = $content.IndexOf($ConstantsEndMarker)
    $entries = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $entries += "  public static final class $($metadata.PascalName) extends frc.robot.constants.$($metadata.PascalName)Constants {}"
    }

    $block = if ($entries.Count -eq 0) { "" } else { "`n" + ($entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Rewrite-StateMachineBlock {
    param(
        [Parameter(Mandatory = $true)][string]$StateMachinePath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $content = Get-Content -Path $StateMachinePath -Raw
    if (-not $content.Contains($StateMachineStartMarker) -or -not $content.Contains($StateMachineEndMarker)) {
        throw "Could not find POWERLIB GENERATED SUBSYSTEMS markers in StateMachine.java. Re-run the installer or add the DO NOT DELETE markers manually."
    }

    $fields = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $fields += "  public final $($metadata.SubsystemClassName) $($metadata.CamelName) = new $($metadata.SubsystemClassName)(Constants.$($metadata.PascalName).$($metadata.ConfigConstantName));"
    }

    $start = $content.IndexOf($StateMachineStartMarker) + $StateMachineStartMarker.Length
    $end = $content.IndexOf($StateMachineEndMarker)
    $block = if ($fields.Count -eq 0) { "`n" } else { "`n" + ($fields -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $StateMachinePath -Value $updated -Encoding ascii
}

function Get-PreservedCustomConstantsBlock {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return $null
    }

    $content = Get-Content -Path $Path -Raw -Encoding UTF8
    if (-not $content.Contains($CustomConstantsStartMarker) -or -not $content.Contains($CustomConstantsEndMarker)) {
        return $null
    }

    $start = $content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $content.IndexOf($CustomConstantsEndMarker)
    return $content.Substring($start, $end - $start).Trim("`r", "`n")
}

function Get-SubsystemIdFromGeneratedContent {
    param([Parameter(Mandatory = $true)][string]$Content)

    foreach ($line in ($Content -split "`r?`n")) {
        if ($line.StartsWith($SubsystemIdMarkerPrefix)) {
            return $line.Substring($SubsystemIdMarkerPrefix.Length).Trim()
        }
    }

    return $null
}

function Get-CustomConstantsBySubsystemId {
    param([Parameter(Mandatory = $true)][string]$ConstantsDir)

    $customBlocks = @{}
    if (-not (Test-Path $ConstantsDir)) {
        return $customBlocks
    }

    Get-ChildItem -Path $ConstantsDir -Filter "*Constants.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw -Encoding UTF8
        if (-not $content.Contains($GeneratedFileMarkerPrefix)) {
            return
        }

        $id = Get-SubsystemIdFromGeneratedContent $content
        if (-not [string]::IsNullOrWhiteSpace($id)) {
            $customBlock = Get-PreservedCustomConstantsBlock $_.FullName
            if (-not [string]::IsNullOrWhiteSpace($customBlock)) {
                $customBlocks[$id] = $customBlock
            }
        }
    }

    return $customBlocks
}

function Set-CustomConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [AllowNull()][string]$CustomContent
    )

    if ([string]::IsNullOrWhiteSpace($CustomContent)) {
        return $Content
    }

    $start = $Content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $Content.IndexOf($CustomConstantsEndMarker)
    if ($start -lt $CustomConstantsStartMarker.Length -or $end -lt 0) {
        return $Content
    }

    return $Content.Substring(0, $start) + "`n" + $CustomContent.Trim("`r", "`n") + "`n" + $Content.Substring($end)
}

function Write-ConstantsFile {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata,
        [Parameter(Mandatory = $true)]$CustomBlocksById
    )

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    New-Item -ItemType Directory -Force -Path $constantsDir | Out-Null

    $outputFile = Join-Path $constantsDir "$($Metadata.PascalName)Constants.java"
    $customContent = if ($CustomBlocksById.ContainsKey($Metadata.Id)) {
        $CustomBlocksById[$Metadata.Id]
    } else {
        Get-PreservedCustomConstantsBlock $outputFile
    }
    $content = switch ($Metadata.Type) {
        "velocity" { New-VelocityConstantsContent $Subsystem $Metadata }
        "velocitytorque" { New-VelocityConstantsContent $Subsystem $Metadata }
        "absoluteposition" { New-AbsolutePositionConstantsContent $Subsystem $Metadata }
        "relativeposition" { New-RelativePositionConstantsContent $Subsystem $Metadata }
    }
    $content = Set-CustomConstantsBlock $content $customContent

    Set-Content -Path $outputFile -Value $content -Encoding ascii
    return $outputFile
}

function Write-SwerveConstantsFile {
    param([Parameter(Mandatory = $true)]$SwerveConfig)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    New-Item -ItemType Directory -Force -Path $constantsDir | Out-Null

    $outputFile = Join-Path $constantsDir "SwerveConstants.java"
    $customContent = Get-PreservedCustomConstantsBlock $outputFile
    $content = Set-CustomConstantsBlock (New-SwerveConstantsContent $SwerveConfig) $customContent
    Set-Content -Path $outputFile -Value $content -Encoding ascii
    return $outputFile
}

function New-VelocityCharacterizationContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    return @"
package frc.robot.characterization;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import static edu.wpi.first.units.Units.Radians;
import static edu.wpi.first.units.Units.RadiansPerSecond;
import static edu.wpi.first.units.Units.Volts;

import com.ctre.phoenix6.SignalLogger;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.powerlib.subsystems.VelocitySubsystem;

public class $($Metadata.PascalName)Characterization {
  private final VelocitySubsystem subsystem;
  private final SysIdRoutine routine;
  private final double[] lastVoltage = {0};

  public $($Metadata.PascalName)Characterization(VelocitySubsystem subsystem) {
    this.subsystem = subsystem;
    this.routine =
        new SysIdRoutine(
            new SysIdRoutine.Config(
                null,
                Volts.of(4),
                null,
                state -> SignalLogger.writeString("SysId$($Metadata.PascalName)_State", state.toString())),
            new SysIdRoutine.Mechanism(
                voltage -> {
                  lastVoltage[0] = voltage.in(Volts);
                  subsystem.setVoltage(voltage.in(Volts));
                },
                log -> {
                  var motor = subsystem.getVelocityMotor();
                  if (motor == null) {
                    return;
                  }
                  double posRot = motor.getRotorPosition().getValueAsDouble();
                  double velRps = motor.getRotorVelocity().getValueAsDouble();
                  log
                      .motor("$($Metadata.PascalName)")
                      .voltage(Volts.of(lastVoltage[0]))
                      .angularPosition(Radians.of(posRot * 2 * Math.PI))
                      .angularVelocity(RadiansPerSecond.of(velRps * 2 * Math.PI));
                },
                subsystem,
                "$($Metadata.PascalName)"));
  }

  public Command quasistaticForward() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kForward));
  }

  public Command quasistaticReverse() {
    return withLogging(routine.quasistatic(SysIdRoutine.Direction.kReverse));
  }

  public Command dynamicForward() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kForward));
  }

  public Command dynamicReverse() {
    return withLogging(routine.dynamic(SysIdRoutine.Direction.kReverse));
  }

  private Command withLogging(Command command) {
    return Commands.sequence(
        Commands.runOnce(() -> SignalLogger.start()),
        command,
        Commands.runOnce(() -> SignalLogger.stop()));
  }
}
"@
}

function Write-CharacterizationFile {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    if ($Metadata.Type -ne "velocity" -and $Metadata.Type -ne "velocitytorque") {
        return $null
    }

    $characterizationDir = Join-Path (Get-Location) "src/main/java/frc/robot/characterization"
    New-Item -ItemType Directory -Force -Path $characterizationDir | Out-Null

    $outputFile = Join-Path $characterizationDir "$($Metadata.PascalName)Characterization.java"
    Set-Content -Path $outputFile -Value (New-VelocityCharacterizationContent $Subsystem $Metadata) -Encoding ascii
    return $outputFile
}

function Ensure-PowerDashboardRawNetworkTablesSupport {
    param([Parameter(Mandatory = $true)][string]$PowerDashboardPath)

    $content = Get-Content -Path $PowerDashboardPath -Raw
    if ($content.Contains("registerCharacterizationCommand(") -and $content.Contains('getSubTable("Subsystems")') -and $content.Contains('getSubTable("Tuning")') -and $content.Contains("RequestedEnabled") -and $content.Contains("TUNING_MODE_SYNC_INTERVAL_SECONDS") -and -not $content.Contains("SmartDashboard")) {
        return
    }

    $rawPowerDashboard = @'
// Copyright (c) FIRST and other WPILib contributors.
// Open Source Software; you can modify and/or share it under the terms of
// the WPILib BSD license file in the root directory of this project.

package frc.robot.subsystems;

import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableEntry;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.CommandScheduler;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import frc.powerlib.PowerRobotContainer;
import java.util.HashMap;
import java.util.Map;

public class PowerDashboard extends SubsystemBase {
  private static final double TUNING_MODE_SYNC_INTERVAL_SECONDS = 1.0;

  private final StateMachine stateMachine;
  private final NetworkTable subsystemsTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Subsystems");
  private final NetworkTable commandsTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Commands");
  private final NetworkTable tuningTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Tuning");
  private final NetworkTableEntry tuningEnabledEntry = tuningTable.getEntry("Enabled");
  private final NetworkTableEntry tuningRequestedEntry = tuningTable.getEntry("RequestedEnabled");
  private final NetworkTable characterizationTable =
      NetworkTableInstance.getDefault().getTable("PowerLib").getSubTable("Characterization");
  private final Map<String, CharacterizationCommandBinding> characterizationCommands = new HashMap<>();
  private double nextTuningModeSyncTime = 0.0;

  public PowerDashboard(StateMachine stateMachine) {
    this.stateMachine = stateMachine;
    initCharacterizationRoutines();
  }

  private void initCharacterizationRoutines() {
    // POWERLIB GENERATED CHARACTERIZATION START - DO NOT DELETE
    // POWERLIB GENERATED CHARACTERIZATION END - DO NOT DELETE
  }

  @Override
  public void periodic() {
    syncTuningMode();
    publishSubsystemData();
    syncSubsystemVariables();
    syncCommandVariables();
    pollCharacterizationCommands();
  }

  private void syncTuningMode() {
    double now = Timer.getFPGATimestamp();
    if (now < nextTuningModeSyncTime) {
      return;
    }

    nextTuningModeSyncTime = now + TUNING_MODE_SYNC_INTERVAL_SECONDS;
    boolean currentEnabled = PowerRobotContainer.isTuningEnabled();
    boolean requestedEnabled = tuningRequestedEntry.getBoolean(currentEnabled);
    PowerRobotContainer.setTuningEnabled(requestedEnabled);
    tuningEnabledEntry.setBoolean(requestedEnabled);
  }

  private void publishSubsystemData() {
    frc.powerlib.dashboard.SubsystemTelemetry.publish();
  }

  private void syncSubsystemVariables() {
    syncVariables(
        PowerRobotContainer.getAllSubsystemVariables(),
        subsystemsTable,
        PowerRobotContainer::updateSubsystemVariable);
  }

  private void syncCommandVariables() {
    syncVariables(
        PowerRobotContainer.getAllCommandVariables(),
        commandsTable,
        PowerRobotContainer::updateCommandVariable);
  }

  private void syncVariables(
      Map<String, Map<String, Object>> variablesByOwner,
      NetworkTable ownerTable,
      VariableUpdater updater) {
    new java.util.HashMap<>(variablesByOwner)
        .forEach(
            (ownerName, variables) -> {
              NetworkTable variablesTable = ownerTable.getSubTable(ownerName).getSubTable("Variables");
              new java.util.HashMap<>(variables)
                  .forEach(
                      (key, defaultValue) -> {
                        Object value =
                            syncVariable(
                                variablesTable.getEntry(key),
                                defaultValue,
                                PowerRobotContainer.isTuningEnabled());
                        updater.update(ownerName, key, value);
                      });
            });
  }

  private Object syncVariable(NetworkTableEntry entry, Object defaultValue, boolean tuningEnabled) {
    if (defaultValue instanceof Boolean) {
      boolean fallback = (Boolean) defaultValue;
      if (!entry.exists()) {
        entry.setBoolean(fallback);
      }
      if (!tuningEnabled) {
        return fallback;
      }
      return entry.getBoolean(fallback);
    }

    if (defaultValue instanceof Number) {
      double fallback = ((Number) defaultValue).doubleValue();
      if (!entry.exists()) {
        entry.setDouble(fallback);
      }
      if (!tuningEnabled) {
        return fallback;
      }
      return entry.getDouble(fallback);
    }

    String fallback = defaultValue == null ? "" : defaultValue.toString();
    if (!entry.exists()) {
      entry.setString(fallback);
    }
    if (!tuningEnabled) {
      return fallback;
    }
    return entry.getString(fallback);
  }

  private void publishValue(NetworkTable table, String key, Object value) {
    NetworkTableEntry entry = table.getEntry(key);
    if (value instanceof Boolean) {
      entry.setBoolean((Boolean) value);
      return;
    }

    if (value instanceof Number) {
      entry.setDouble(((Number) value).doubleValue());
      return;
    }

    entry.setString(value == null ? "" : value.toString());
  }

  private interface VariableUpdater {
    void update(String ownerName, String key, Object value);
  }

  private void registerCharacterizationCommand(String subsystemName, String commandName, Command command) {
    NetworkTable commandTable = characterizationTable.getSubTable(subsystemName).getSubTable(commandName);
    NetworkTableEntry requestEntry = commandTable.getEntry("request");
    NetworkTableEntry runningEntry = commandTable.getEntry("running");

    commandTable.getEntry(".type").setString("PowerLibCommand");
    commandTable.getEntry("name").setString(commandName);
    requestEntry.setBoolean(false);
    runningEntry.setBoolean(false);
    characterizationCommands.put(
        subsystemName + "/" + commandName,
        new CharacterizationCommandBinding(command, requestEntry, runningEntry));
  }

  private void pollCharacterizationCommands() {
    CommandScheduler scheduler = CommandScheduler.getInstance();
    characterizationCommands.values().forEach(
        binding -> {
          if (binding.requestEntry.getBoolean(false)) {
            binding.requestEntry.setBoolean(false);
            if (!scheduler.isScheduled(binding.command)) {
              scheduler.schedule(binding.command);
            }
          }

          binding.runningEntry.setBoolean(scheduler.isScheduled(binding.command));
        });
  }

  private static class CharacterizationCommandBinding {
    private final Command command;
    private final NetworkTableEntry requestEntry;
    private final NetworkTableEntry runningEntry;

    private CharacterizationCommandBinding(
        Command command, NetworkTableEntry requestEntry, NetworkTableEntry runningEntry) {
      this.command = command;
      this.requestEntry = requestEntry;
      this.runningEntry = runningEntry;
    }
  }
}
'@

    Set-Content -Path $PowerDashboardPath -Value $rawPowerDashboard -Encoding ascii
}

function Rewrite-PowerDashboardCharacterizationBlock {
    param(
        [Parameter(Mandatory = $true)][string]$PowerDashboardPath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $content = Get-Content -Path $PowerDashboardPath -Raw
    if (-not $content.Contains($CharacterizationStartMarker) -or -not $content.Contains($CharacterizationEndMarker)) {
        throw "Could not find POWERLIB GENERATED CHARACTERIZATION markers in PowerDashboard.java. Re-run the installer or add the DO NOT DELETE markers manually."
    }

    $velocitySubsystems = @($Subsystems | Where-Object {
        $type = $_.type.ToString().ToLowerInvariant()
        $type -eq "velocity" -or $type -eq "velocitytorque"
    })
    $imports = @($velocitySubsystems | ForEach-Object {
        $metadata = Get-SubsystemMetadata $_
        "import frc.robot.characterization.$($metadata.PascalName)Characterization;"
    })

    $content = [regex]::Replace(
        $content,
        "(?m)^import frc\.robot\.characterization\.[A-Za-z0-9_]+Characterization;\r?\n",
        ""
    )

    if ($imports.Count -gt 0) {
        $lastImportMatch = [regex]::Matches($content, "(?m)^import .+;\r?$") | Select-Object -Last 1
        if ($null -ne $lastImportMatch) {
            $insertAt = $lastImportMatch.Index + $lastImportMatch.Length
            $content = $content.Substring(0, $insertAt) + "`n" + ($imports -join "`n") + $content.Substring($insertAt)
        }
    }

    $entries = @()
    foreach ($subsystem in $velocitySubsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $fieldName = "$($metadata.CamelName)Characterization"
        $entries += "    var $fieldName = new $($metadata.PascalName)Characterization(stateMachine.$($metadata.CamelName));"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Quasistatic Forward`", $fieldName.quasistaticForward());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Quasistatic Reverse`", $fieldName.quasistaticReverse());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Dynamic Forward`", $fieldName.dynamicForward());"
        $entries += "    registerCharacterizationCommand(`"$($metadata.PascalName)`", `"Dynamic Reverse`", $fieldName.dynamicReverse());"
    }

    $start = $content.IndexOf($CharacterizationStartMarker) + $CharacterizationStartMarker.Length
    $end = $content.IndexOf($CharacterizationEndMarker)
    $block = if ($entries.Count -eq 0) { "`n" } else { "`n" + ($entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $PowerDashboardPath -Value $updated -Encoding ascii
}

function Remove-DeletedGeneratedFiles {
    param([Parameter(Mandatory = $true)]$Subsystems)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"

    $wantedFiles = @{}
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $wantedFiles["$($metadata.PascalName)Constants.java"] = $true
    }

    if (Test-Path $constantsDir) {
        Get-ChildItem -Path $constantsDir -Filter "*Constants.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarkerPrefix) -and -not $wantedFiles.ContainsKey($_.Name)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted removed subsystem constants $($_.Name)"
            }
        }
    }

    Remove-LegacyGeneratedSubsystemFiles
}

function Remove-LegacyGeneratedSubsystemFiles {
    $subsystemsDir = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems"
    if (Test-Path $subsystemsDir) {
        Get-ChildItem -Path $subsystemsDir -Filter "*.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarkerPrefix)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted legacy generated subsystem $($_.Name)"
            }
        }
    }

    $ioDir = Join-Path $subsystemsDir "io"
    if (Test-Path $ioDir) {
        Get-ChildItem -Path $ioDir -Filter "*.java" -File | ForEach-Object {
            $content = Get-Content -Path $_.FullName -Raw
            if ($content.Contains($GeneratedFileMarkerPrefix)) {
                Remove-Item -LiteralPath $_.FullName -Force
                Write-Host "Deleted legacy generated subsystem IO $($_.Name)"
            }
        }
    }
}

function Remove-StaleCharacterizationFiles {
    param([Parameter(Mandatory = $true)]$Subsystems)

    $characterizationDir = Join-Path (Get-Location) "src/main/java/frc/robot/characterization"
    if (-not (Test-Path $characterizationDir)) {
        return
    }

    $wantedFiles = @{}
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        if ($metadata.Type -eq "velocity" -or $metadata.Type -eq "velocitytorque") {
            $wantedFiles["$($metadata.PascalName)Characterization.java"] = $true
        }
    }

    Get-ChildItem -Path $characterizationDir -Filter "*Characterization.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw
        if ($content.Contains($GeneratedFileMarkerPrefix) -and -not $wantedFiles.ContainsKey($_.Name)) {
            Remove-Item -LiteralPath $_.FullName -Force
            Write-Host "Deleted stale characterization $($_.Name)"
        }
    }
}

function Format-JavaDoubleLiteral {
    param([Parameter(Mandatory = $true)]$Value)

    $text = $Value.ToString()
    if ($text -notmatch '\.' -and $text -notmatch '[eE]') {
        $text = "$text.0"
    }

    return $text
}

function Write-TunableConstantsRegistry {
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()]$Subsystems)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    $classNames = @("Vision", "StateMachine", "OI", "RobotContainer", "Swerve")
    foreach ($subsystem in @($Subsystems)) {
        $classNames += (Get-SubsystemMetadata $subsystem).PascalName
    }
    $registrations = @()
    foreach ($className in $classNames) {
        if (Test-Path (Join-Path $constantsDir "${className}Constants.java")) {
            $registrations += "    TunableConstants.register(${className}Constants.class);"
        }
    }
    $content = @"
package frc.robot.constants;

import frc.powerlib.tuning.TunableConstants;

public final class GeneratedTunableConstants {
  private GeneratedTunableConstants() {}

  public static void register() {
$($registrations -join "`n")
  }
}
"@
    Set-Content -Path (Join-Path $constantsDir "GeneratedTunableConstants.java") -Value $content -Encoding ascii
}

function Get-JavaConstantRows {
    param([Parameter(Mandatory = $true)][AllowEmptyString()][string]$Source)

    $masked = [regex]::Replace($Source, '/\*[\s\S]*?\*/|//[^\r\n]*|"""[\s\S]*?"""|"(?:\\[\s\S]|[^"\\])*"|''(?:\\[\s\S]|[^''\\])*''', {
        param($matchResult)
        return [regex]::Replace($matchResult.Value, '[^\r\n]', ' ')
    })
    $pattern = '(?:(@(?:frc\.powerlib\.tuning\.)?TunableConstant)\s+)?\bpublic\s+static\s+(?:final|volatile)\s+([\w.$<>?,\s\[\]]+?)\s+([A-Za-z_$][\w$]*)\s*='
    $customStart = $Source.IndexOf($CustomConstantsStartMarker)
    $customEnd = $Source.IndexOf($CustomConstantsEndMarker)
    foreach ($matchResult in [regex]::Matches($masked, $pattern)) {
        $prefix = $masked.Substring(0, $matchResult.Index)
        if (([regex]::Matches($prefix, '\{').Count - [regex]::Matches($prefix, '\}').Count) -ne 1) { continue }
        $expressionStart = $matchResult.Index + $matchResult.Length
        $nesting = 0
        $end = $expressionStart
        for (; $end -lt $masked.Length; $end++) {
            $char = $masked[$end]
            if ('([{'.Contains($char)) { $nesting++ }
            if (')]}'.Contains($char)) { $nesting-- }
            if ($char -eq ';' -and $nesting -eq 0) { break }
        }
        if ($end -eq $masked.Length) { throw "Missing semicolon for constant $($matchResult.Groups[3].Value)." }
        [pscustomobject]@{
            name = $matchResult.Groups[3].Value
            type = $matchResult.Groups[2].Value.Trim()
            value = $Source.Substring($expressionStart, $end - $expressionStart).Trim()
            custom = $customStart -ge 0 -and $matchResult.Index -gt $customStart -and $end -lt $customEnd
            tunable = $matchResult.Groups[1].Success
            start = $matchResult.Index
            end = $end + 1
        }
    }
}

function Test-NumericConstantType {
    param([Parameter(Mandatory = $true)][string]$Type)
    return $Type.Trim() -cmatch '^(byte|short|int|long|float|double|(java\.lang\.)?(Byte|Short|Integer|Long|Float|Double))$'
}

function Read-ConstantsConfiguration {
    $path = Join-Path (Get-Location) 'power-tool/generated/powerlib-constants.json'
    if (-not (Test-Path $path)) { return [pscustomobject]@{ version = 1; files = [pscustomobject]@{} } }
    $configuration = Get-Content -LiteralPath $path -Raw -Encoding UTF8 | ConvertFrom-Json
    if ($configuration.version -ne 1 -or -not (Test-IsJsonObject $configuration.files)) { throw 'Invalid powerlib-constants.json configuration.' }
    return $configuration
}

function Get-ConstantsConfigurationTargets {
    param([Parameter(Mandatory = $true)][AllowEmptyCollection()]$Subsystems)
    foreach ($name in @('Vision', 'StateMachine', 'OI', 'RobotContainer', 'Swerve')) {
        [pscustomobject]@{ key = "robot:$name"; name = $name; customOnly = $false }
    }
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        [pscustomobject]@{ key = "subsystem:$($metadata.Id)"; name = $metadata.PascalName; customOnly = $true }
    }
}

function Import-ConstantsConfiguration {
    param([Parameter(Mandatory = $true)]$Configuration, [Parameter(Mandatory = $true)][AllowEmptyCollection()]$Subsystems, [Parameter(Mandatory = $true)]$CustomBlocksById)
    $directory = Join-Path (Get-Location) 'src/main/java/frc/robot/constants'
    foreach ($target in @(Get-ConstantsConfigurationTargets $Subsystems)) {
        if ($null -ne $Configuration.files.PSObject.Properties[$target.key]) { continue }
        $path = Join-Path $directory "$($target.name)Constants.java"
        $source = if (Test-Path $path) { Get-Content -LiteralPath $path -Raw -Encoding UTF8 } else { '' }
        if ($target.customOnly -and $CustomBlocksById.ContainsKey($target.key.Substring('subsystem:'.Length))) {
            $source = "public class Imported {`n$CustomConstantsStartMarker`n$($CustomBlocksById[$target.key.Substring('subsystem:'.Length)])`n$CustomConstantsEndMarker`n}"
        }
        if ([string]::IsNullOrWhiteSpace($source) -and -not $target.customOnly) { continue }
        $constants = @(Get-JavaConstantRows $source | Where-Object { (-not $target.customOnly -or $_.custom) -and ($target.name -ne 'Swerve' -or $_.custom) } | ForEach-Object {
            [pscustomobject]@{ name = $_.name; type = $_.type; value = $_.value; custom = $_.custom; tunable = Test-NumericConstantType $_.type }
        })
        $Configuration.files | Add-Member -MemberType NoteProperty -Name $target.key -Value ([pscustomobject]@{ constants = $constants })
    }
}

function Move-ControllerPortToOI {
    param([Parameter(Mandatory = $true)]$Configuration)

    $directory = Join-Path (Get-Location) 'src/main/java/frc/robot/constants'
    $oldPath = Join-Path $directory 'RobotContainerConstants.java'
    $oiPath = Join-Path $directory 'OIConstants.java'
    $oldSource = if (Test-Path $oldPath) { Get-Content -LiteralPath $oldPath -Raw -Encoding UTF8 } else { '' }
    $original = Get-JavaConstantRows $oldSource | Where-Object { -not $_.custom -and $_.name -ceq 'DRIVER_CONTROLLER_PORT' } | Select-Object -First 1
    $oldEntry = $Configuration.files.PSObject.Properties['robot:RobotContainer']
    $port = if ($null -ne $oldEntry) { $oldEntry.Value.constants | Where-Object { -not $_.custom -and $_.name -ceq 'DRIVER_CONTROLLER_PORT' } | Select-Object -First 1 } else { $null }
    if ($null -eq $port) { $port = $original }
    if ($null -ne $port) {
        if (-not (Test-Path $oiPath)) { throw 'Missing OIConstants.java for controller port migration.' }
        $oiSource = Get-Content -LiteralPath $oiPath -Raw -Encoding UTF8
        $existingPort = Get-JavaConstantRows $oiSource | Where-Object { $_.name -ceq 'DRIVER_CONTROLLER_PORT' } | Select-Object -First 1
        if ($null -eq $existingPort) {
            $pattern = '(public\s+class\s+OIConstants\s*\{)'
            if (-not [regex]::IsMatch($oiSource, $pattern)) { throw 'Could not find OIConstants class for controller port migration.' }
            $oiSource = [regex]::Replace($oiSource, $pattern, ('$1' + "`n  public static final int DRIVER_CONTROLLER_PORT = $($port.value);`n"))
            [System.IO.File]::WriteAllText($oiPath, $oiSource, [System.Text.UTF8Encoding]::new($false))
        }
        if ($null -ne $original) {
            $oldSource = $oldSource.Remove($original.start, $original.end - $original.start)
            [System.IO.File]::WriteAllText($oldPath, $oldSource, [System.Text.UTF8Encoding]::new($false))
        }
        if ($null -ne $oldEntry) {
            $oldEntry.Value.constants = @($oldEntry.Value.constants | Where-Object { $_.custom -or $_.name -cne 'DRIVER_CONTROLLER_PORT' })
        }
        $oiEntry = $Configuration.files.PSObject.Properties['robot:OI']
        if ($null -eq $oiEntry) {
            $Configuration.files | Add-Member -MemberType NoteProperty -Name 'robot:OI' -Value ([pscustomobject]@{ constants = @() })
            $oiEntry = $Configuration.files.PSObject.Properties['robot:OI']
        }
        $oiEntry.Value.constants = @($oiEntry.Value.constants | Where-Object { $_.name -cne 'DRIVER_CONTROLLER_PORT' }) + @(
            [pscustomobject]@{ name = 'DRIVER_CONTROLLER_PORT'; type = 'int'; value = $port.value; custom = $false; tunable = $true }
        )
    }
    $containerPath = Join-Path (Get-Location) 'src/main/java/frc/robot/RobotContainer.java'
    if (Test-Path $containerPath) {
        $source = Get-Content -LiteralPath $containerPath -Raw -Encoding UTF8
        $updated = $source.Replace('Constants.RobotContainer.DRIVER_CONTROLLER_PORT', 'Constants.OI.DRIVER_CONTROLLER_PORT')
        if ($updated -cne $source) {
            [System.IO.File]::WriteAllText($containerPath, $updated, [System.Text.UTF8Encoding]::new($false))
        }
    }
}

function Format-ConfiguredConstant {
    param([Parameter(Mandatory = $true)]$Constant)
    if ($Constant.name -cnotmatch '^[A-Za-z_$][\w$]*$' -or [string]::IsNullOrWhiteSpace($Constant.value) -or $Constant.type -cnotmatch '^[A-Za-z_$][\w.$]*(\s*<\s*[\w.$?,<>\s]+>)?(\s*\[\])*\s*$') { throw 'Invalid constant in powerlib-constants.json.' }
    $numeric = Test-NumericConstantType $Constant.type
    $annotation = if ($numeric) { "@frc.powerlib.tuning.TunableConstant`n  " } else { '' }
    $modifier = if ($numeric) { 'volatile' } else { 'final' }
    return "${annotation}public static $modifier $($Constant.type) $($Constant.name) = $($Constant.value);"
}

function Write-ConfiguredConstants {
    param([Parameter(Mandatory = $true)]$Configuration, [Parameter(Mandatory = $true)][AllowEmptyCollection()]$Subsystems)
    $directory = Join-Path (Get-Location) 'src/main/java/frc/robot/constants'
    foreach ($target in @(Get-ConstantsConfigurationTargets $Subsystems)) {
        if ($null -eq $Configuration.files.PSObject.Properties[$target.key]) { continue }
        $path = Join-Path $directory "$($target.name)Constants.java"
        if (-not (Test-Path $path)) { continue }
        $source = Get-Content -LiteralPath $path -Raw -Encoding UTF8
        $constants = @($Configuration.files.PSObject.Properties[$target.key].Value.constants)
        $parsed = @(Get-JavaConstantRows $source)
        foreach ($original in @($parsed | Sort-Object start -Descending)) {
            if ($original.custom -or $target.customOnly -or $target.name -eq 'Swerve') { continue }
            $constant = $constants | Where-Object { -not $_.custom -and $_.name -ceq $original.name } | Select-Object -First 1
            if ($null -eq $constant) { continue }
            if ($constant.type -cne $original.type) { throw "Saved type of $($constant.name) does not match robot code." }
            $source = $source.Substring(0, $original.start) + (Format-ConfiguredConstant $constant) + $source.Substring($original.end)
        }
        $customContent = @($constants | Where-Object { $_.custom } | ForEach-Object { '  ' + (Format-ConfiguredConstant $_) }) -join "`n"
        $start = $source.IndexOf($CustomConstantsStartMarker)
        $end = $source.IndexOf($CustomConstantsEndMarker)
        if ($start -lt 0 -and $end -lt 0) {
            $closing = $source.LastIndexOf('}')
            $source = $source.Substring(0, $closing) + "$CustomConstantsStartMarker`n$CustomConstantsEndMarker`n" + $source.Substring($closing)
            $start = $source.IndexOf($CustomConstantsStartMarker)
            $end = $source.IndexOf($CustomConstantsEndMarker)
        }
        if ($start -lt 0 -or $end -le $start) { throw "Invalid custom constants markers in $path." }
        $start += $CustomConstantsStartMarker.Length
        $source = $source.Substring(0, $start) + "`n$customContent`n" + $source.Substring($end)
        [System.IO.File]::WriteAllText($path, $source + "`n", [System.Text.UTF8Encoding]::new($false))
    }
    [System.IO.File]::WriteAllText((Join-Path (Get-Location) 'power-tool/generated/powerlib-constants.json'), ($Configuration | ConvertTo-Json -Depth 16) + "`n", [System.Text.UTF8Encoding]::new($false))
}
function Ensure-SwerveCachedTuningSupport {
    param([Parameter(Mandatory = $true)][string]$SwervePath)

    if (-not (Test-Path -LiteralPath $SwervePath)) { return }
    $content = Get-Content -LiteralPath $SwervePath -Raw -Encoding UTF8
    $pattern = '(?m)^  private void applyTunableValues\(\) \{'
    # Custom drivetrains without the PowerLib tuning methods are managed by their owner.
    if (-not [regex]::IsMatch($content, $pattern)) { return }
    $syncCall = 'frc.powerlib.utils.DriveUtil.syncTunableValues();'
    if (-not $content.Contains($syncCall)) {
        $guard = @"
    if (!PowerRobotContainer.isTuningEnabled()) {
      return;
    }
    $syncCall
"@
        $content = [regex]::Replace($content, $pattern, ('$0' + "`n" + $guard))
    }
    $pattern = '(?m)(^  private double getSwerveVariable\(String key, double defaultValue\) \{\r?\n)    if \(!PowerRobotContainer\.isTuningEnabled\(\)\) \{\r?\n      return defaultValue;\r?\n    \}\r?\n\r?\n'
    $content = [regex]::Replace($content, $pattern, '$1')
    [System.IO.File]::WriteAllText($SwervePath, $content, [System.Text.UTF8Encoding]::new($false))
}

function Ensure-SubsystemTelemetrySupport {
    param([Parameter(Mandatory = $true)][string]$PowerDashboardPath)

    $content = Get-Content -Path $PowerDashboardPath -Raw
    $content = [regex]::Replace($content,
        '(?ms)^  private void publishSubsystemData\(\) \{.*?^  \}',
        "  private void publishSubsystemData() {`n    frc.powerlib.dashboard.SubsystemTelemetry.publish();`n  }")
    $content = [regex]::Replace($content,
        '(?ms)^  private void publishValue\(NetworkTable table, String key, Object value\) \{.*?^  \}\r?\n\r?\n', '')

    if (-not $content.Contains('private final frc.powerlib.dashboard.DriveTelemetry driveTelemetry;')) {
        $content = $content.Replace('  private final StateMachine stateMachine;',
            "  private final StateMachine stateMachine;`n  private final frc.powerlib.dashboard.DriveTelemetry driveTelemetry;")
        $driveInitialization = @'
    this.stateMachine = stateMachine;
    driveTelemetry = new frc.powerlib.dashboard.DriveTelemetry()
        .withPose(() -> stateMachine.drivetrain.getState().Pose)
        .withSpeeds(() -> stateMachine.drivetrain.getState().Speeds)
        .withState(() -> stateMachine.getWantedState().name());
'@
        $content = $content.Replace('    this.stateMachine = stateMachine;', $driveInitialization)
    }
    if (-not $content.Contains('driveTelemetry.publish();')) {
        $content = $content.Replace('  public void periodic() {',
            "  public void periodic() {`n    driveTelemetry.publish();")
    }
    Set-Content -Path $PowerDashboardPath -Value $content -Encoding ascii
}

function Ensure-TunableConstantsSupport {
    param([Parameter(Mandatory = $true)][string]$PowerDashboardPath)

    $content = Get-Content -Path $PowerDashboardPath -Raw -Encoding UTF8
    $registerCall = "frc.robot.constants.GeneratedTunableConstants.register();"
    $syncCall = "frc.powerlib.tuning.TunableConstants.sync();"
    if (-not $content.Contains($registerCall)) {
        $pattern = '(public\s+PowerDashboard\s*\(\s*StateMachine\s+\w+\s*\)\s*\{)'
        if (-not [regex]::IsMatch($content, $pattern)) { throw "Could not find PowerDashboard constructor for tunable constants registration." }
        $content = [regex]::Replace($content, $pattern, ('$1' + "`n    $registerCall"))
    }
    if (-not $content.Contains($syncCall)) {
        $pattern = 'syncSubsystemVariables\(\);'
        if (-not [regex]::IsMatch($content, $pattern)) { throw "Could not find PowerDashboard subsystem variable synchronization." }
        $content = [regex]::Replace($content, $pattern, ("syncSubsystemVariables();`n    $syncCall"))
    }
    foreach ($scope in @('Subsystem', 'Command')) {
        $field = "synced${scope}VariablesRevision"
        if (-not $content.Contains("private long $field")) {
            $pattern = '(?m)^  private double nextTuningModeSyncTime = 0\.0;'
            if (-not [regex]::IsMatch($content, $pattern)) { throw "Could not find PowerDashboard tuning state." }
            $content = [regex]::Replace($content, $pattern, ('$0' + "`n  private long $field = -1;"))
        }
        if ($content.Contains("revision == $field")) { continue }
        $ownerTable = if ($scope -eq 'Subsystem') { 'subsystemsTable' } else { 'commandsTable' }
        $method = @"
  private void sync${scope}Variables() {
    long revision = PowerRobotContainer.get${scope}VariablesRevision();
    if (!PowerRobotContainer.isTuningEnabled() && revision == $field) {
      return;
    }
    syncVariables(
        PowerRobotContainer.getAll${scope}Variables(),
        $ownerTable,
        PowerRobotContainer::update${scope}Variable);
    $field = revision;
  }
"@
        $pattern = '(?ms)^  private void sync' + $scope + 'Variables\(\) \{.*?^  \}'
        if (-not [regex]::IsMatch($content, $pattern)) { throw "Could not find PowerDashboard $scope variable synchronization." }
        $content = [regex]::Replace($content, $pattern, $method)
    }
    [System.IO.File]::WriteAllText($PowerDashboardPath, $content, [System.Text.UTF8Encoding]::new($false))
}

function Update-SubsystemsFromJson {
    param([Parameter(Mandatory = $true)][string]$JsonPath)

    $document = Read-SubsystemDocument $JsonPath
    $subsystems = @($document.subsystems)

    $constantsBarrel = Join-Path (Get-Location) "src/main/java/frc/robot/Constants.java"
    if (-not (Test-Path $constantsBarrel)) {
        throw "Missing src/main/java/frc/robot/Constants.java. Run robotLibraryInstall first."
    }

    $stateMachineFile = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems/StateMachine.java"
    if (-not (Test-Path $stateMachineFile)) {
        throw "Missing src/main/java/frc/robot/subsystems/StateMachine.java. Run robotLibraryInstall first."
    }

    $powerDashboardFile = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems/PowerDashboard.java"
    if (-not (Test-Path $powerDashboardFile)) {
        throw "Missing src/main/java/frc/robot/subsystems/PowerDashboard.java. Run robotLibraryInstall first."
    }

    $written = @()
    $characterizationWritten = @()
    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    $customBlocksById = Get-CustomConstantsBySubsystemId $constantsDir
    $constantsConfiguration = Read-ConstantsConfiguration
    Import-ConstantsConfiguration $constantsConfiguration $subsystems $customBlocksById
    Move-ControllerPortToOI $constantsConfiguration
    $written += Write-SwerveConstantsFile $document.swerve
    foreach ($subsystem in $subsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $written += Write-ConstantsFile $subsystem $metadata $customBlocksById
        $characterizationFile = Write-CharacterizationFile $subsystem $metadata
        if ($null -ne $characterizationFile) {
            $characterizationWritten += $characterizationFile
        }
    }

    Rewrite-ConstantsBlock $constantsBarrel $subsystems
    Rewrite-StateMachineBlock $stateMachineFile $subsystems
    Ensure-PowerDashboardRawNetworkTablesSupport $powerDashboardFile
    Ensure-SubsystemTelemetrySupport $powerDashboardFile
    Write-ConfiguredConstants $constantsConfiguration $subsystems
    Write-TunableConstantsRegistry $subsystems
    Ensure-TunableConstantsSupport $powerDashboardFile
    Ensure-SwerveCachedTuningSupport (Join-Path (Get-Location) 'src/main/java/frc/robot/subsystems/Swerve.java')
    Rewrite-PowerDashboardCharacterizationBlock $powerDashboardFile $subsystems
    Remove-DeletedGeneratedFiles $subsystems
    Remove-StaleCharacterizationFiles $subsystems
    Save-SubsystemDocument $JsonPath $document

    foreach ($file in $written) {
        Write-Host "Generated $file"
    }
    foreach ($file in $characterizationWritten) {
        Write-Host "Generated $file"
    }
    Write-Host "Updated Constants.java, StateMachine.java, and PowerDashboard.java from $JsonPath"
}

function Invoke-BuildIfNeeded {
    if ($SkipBuild) {
        return
    }

    $isWindowsHost = [System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT
    $gradlew = if ($isWindowsHost) { ".\gradlew.bat" } else { "./gradlew" }
    if (Test-Path $gradlew) {
        & $gradlew --no-daemon --console=plain build
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    } else {
        Write-Host "Skipped build because no Gradle wrapper was found."
    }
}

if ($UpdateSubsystems) {
    Update-SubsystemsFromJson $SubsystemsJson
    Invoke-BuildIfNeeded
    exit 0
}

Write-Host "PowerLib subsystem generator starting. Answer the prompts below."
Write-Host "Enum prompts show accepted values before the default."

if ((Test-Path $SubsystemsJson) -and (Prompt-Boolean "Update subsystems from ${SubsystemsJson}?" $true)) {
    Update-SubsystemsFromJson $SubsystemsJson
    Invoke-BuildIfNeeded
    exit 0
}

$document = Read-SubsystemDocument $SubsystemsJson

do {
    $subsystem = New-InteractiveSubsystem
    Upsert-SubsystemDocumentEntry $document $subsystem
    Save-SubsystemDocument $SubsystemsJson $document
    Update-SubsystemsFromJson $SubsystemsJson
    $addAnother = Prompt-Boolean "Add another subsystem?" $false
} while ($addAnother)

Invoke-BuildIfNeeded
