param(
    [switch]$SkipBuild,
    [switch]$UpdateSubsystems,
    [string]$SubsystemsJson = "powerlib-subsystems.json"
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$StateMachineStartMarker = "  // POWERLIB GENERATED SUBSYSTEMS START - DO NOT DELETE"
$StateMachineEndMarker = "  // POWERLIB GENERATED SUBSYSTEMS END - DO NOT DELETE"
$ConstantsStartMarker = "  // POWERLIB GENERATED CONSTANTS START - DO NOT DELETE"
$ConstantsEndMarker = "  // POWERLIB GENERATED CONSTANTS END - DO NOT DELETE"
$GeneratedFileMarker = "// Generated by PowerLib subsystem tool. Edit powerlib-subsystems.json, then run update."
$SubsystemIdMarkerPrefix = "// POWERLIB SUBSYSTEM ID: "
$CustomConstantsStartMarker = "  // POWERLIB CUSTOM CONSTANTS START - DO NOT DELETE"
$CustomConstantsEndMarker = "  // POWERLIB CUSTOM CONSTANTS END - DO NOT DELETE"
$BuiltInConstantNames = @("CanBus", "LED", "Location", "OI", "Tuner", "Vision")

function Prompt-Value {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    $suffix = ""
    if ($null -ne $DefaultValue -and $DefaultValue.Length -gt 0) {
        $suffix = " [$DefaultValue]"
    }

    [Console]::WriteLine()
    [Console]::Write("POWERLIB> $Message$suffix`: ")
    $value = [Console]::ReadLine()
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $DefaultValue
    }

    return $value.Trim()
}

function Prompt-Required {
    param([Parameter(Mandatory = $true)][string]$Message)

    do {
        $value = Prompt-Value $Message
    } while ([string]::IsNullOrWhiteSpace($value))

    return $value.Trim()
}

function Prompt-Enum {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Parameter(Mandatory = $true)][string[]]$AcceptedValues,
        [Parameter(Mandatory = $true)][string]$DefaultValue
    )

    $acceptedText = $AcceptedValues -join ", "
    while ($true) {
        $value = Prompt-Value "$Message (accepted: $acceptedText)" $DefaultValue
        foreach ($accepted in $AcceptedValues) {
            if ($value -ieq $accepted) {
                return $accepted
            }
        }

        Write-Host "Accepted values: $acceptedText"
    }
}

function Prompt-Boolean {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [bool]$DefaultValue = $false
    )

    $defaultText = if ($DefaultValue) { "y" } else { "n" }
    while ($true) {
        $value = (Prompt-Value "$Message (accepted: y, n)" $defaultText).ToLowerInvariant()
        if ($value -eq "y" -or $value -eq "yes" -or $value -eq "true") {
            return $true
        }
        if ($value -eq "n" -or $value -eq "no" -or $value -eq "false") {
            return $false
        }

        Write-Host "Accepted values: y, n"
    }
}

function Prompt-Int {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [Nullable[int]]$DefaultValue = $null
    )

    while ($true) {
        $defaultText = if ($null -eq $DefaultValue) { $null } else { $DefaultValue.ToString() }
        $value = Prompt-Value $Message $defaultText
        $parsed = 0
        if ([int]::TryParse($value, [ref]$parsed)) {
            return $parsed
        }

        Write-Host "Please enter a whole number."
    }
}

function Prompt-DoubleText {
    param(
        [Parameter(Mandatory = $true)][string]$Message,
        [string]$DefaultValue = $null
    )

    while ($true) {
        $value = Prompt-Value $Message $DefaultValue
        $parsed = 0.0
        if ([double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
            return $value
        }

        Write-Host "Please enter a number."
    }
}

function Prompt-OptionalDoubleText {
    param([Parameter(Mandatory = $true)][string]$Label)

    $value = Prompt-Value "$Label (blank for Optional.empty)" ""
    if ([string]::IsNullOrWhiteSpace($value)) {
        return $null
    }

    $parsed = 0.0
    if (-not [double]::TryParse($value, [System.Globalization.NumberStyles]::Float, [System.Globalization.CultureInfo]::InvariantCulture, [ref]$parsed)) {
        throw "Please enter a number for $Label."
    }

    return $value
}

function Get-JavaIdentifierParts {
    param([Parameter(Mandatory = $true)][string]$Value)

    $splitWords = [regex]::Replace($Value, "([a-z])([A-Z])", '$1 $2')
    return @($splitWords -split "[^A-Za-z0-9]+" | Where-Object { $_.Length -gt 0 })
}

function Convert-ToPascalCase {
    param([Parameter(Mandatory = $true)][string]$Value)

    $parts = @(Get-JavaIdentifierParts $Value)
    if ($parts.Count -eq 0) {
        throw "Subsystem name must contain at least one letter or number."
    }

    return ($parts | ForEach-Object {
        $_.Substring(0, 1).ToUpperInvariant() + $_.Substring(1)
    }) -join ""
}

function Convert-ToCamelCase {
    param([Parameter(Mandatory = $true)][string]$Pascal)
    return $Pascal.Substring(0, 1).ToLowerInvariant() + $Pascal.Substring(1)
}

function Convert-ToConstantPrefix {
    param([Parameter(Mandatory = $true)][string]$RawName)
    return (@(Get-JavaIdentifierParts $RawName) | ForEach-Object { $_.ToUpperInvariant() }) -join "_"
}

function Get-StableSubsystemId {
    param([Parameter(Mandatory = $true)]$Subsystem)

    if (($Subsystem.PSObject.Properties.Name -contains "id") -and -not [string]::IsNullOrWhiteSpace($Subsystem.id)) {
        return $Subsystem.id.ToString()
    }

    return Convert-ToCamelCase (Convert-ToPascalCase $Subsystem.name)
}

function Get-SubsystemMetadata {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $pascal = Convert-ToPascalCase $Subsystem.name
    $type = $Subsystem.type.ToString().ToLowerInvariant()
    if ($type -ne "velocity" -and $type -ne "position") {
        throw "Unsupported subsystem type '$($Subsystem.type)' for '$($Subsystem.name)'. Accepted values: velocity, position."
    }

    return [pscustomobject]@{
        Id = Get-StableSubsystemId $Subsystem
        Name = $Subsystem.name
        Type = $type
        PascalName = $pascal
        CamelName = Convert-ToCamelCase $pascal
        ConstantPrefix = Convert-ToConstantPrefix $Subsystem.name
        SubsystemClassName = if ($type -eq "velocity") { "VelocitySubsystem" } else { "PositionSubsystem" }
        ConfigConstantName = "$(Convert-ToConstantPrefix $Subsystem.name)_CONFIG"
    }
}

function Get-NeutralModeExpression {
    param([Parameter(Mandatory = $true)][string]$Value)

    if ($Value -ieq "Coast") {
        return "NeutralModeValue.Coast"
    }
    if ($Value -ieq "Brake") {
        return "NeutralModeValue.Brake"
    }

    throw "Unsupported neutral mode '$Value'. Accepted values: Brake, Coast."
}

function Get-OptionalDoubleExpression {
    param($Value)

    if ($null -eq $Value -or [string]::IsNullOrWhiteSpace($Value.ToString())) {
        return "Optional.empty()"
    }

    return "Optional.of($Value)"
}

function Format-IndentedList {
    param(
        [Parameter(Mandatory = $true)][string[]]$Expressions,
        [Parameter(Mandatory = $true)][string]$Indent
    )

    return ($Expressions | ForEach-Object { "$Indent$_" }) -join ",`n"
}

function Convert-MotorsToExpressions {
    param([Parameter(Mandatory = $true)]$Subsystem)

    $motors = @($Subsystem.motors)
    if ($motors.Count -eq 0) {
        throw "Subsystem '$($Subsystem.name)' must have at least one motor."
    }

    $leader = $motors | Where-Object { $_.role -eq "leader" } | Select-Object -First 1
    if ($null -eq $leader) {
        throw "Subsystem '$($Subsystem.name)' must have one leader motor."
    }

    $lines = @("MotorConfig.leader($($leader.id), $(Get-NeutralModeExpression $leader.neutralMode), $($leader.reversed.ToString().ToLowerInvariant()))")
    foreach ($follower in ($motors | Where-Object { $_.role -eq "follower" })) {
        $lines += "MotorConfig.follower($($follower.id), $($follower.reversed.ToString().ToLowerInvariant()))"
    }

    return $lines
}

function New-InteractiveMotors {
    $leaderId = Prompt-Int "Leader motor CAN ID"
    $neutral = Prompt-Enum "Leader neutral mode" @("Brake", "Coast") "Brake"
    $leaderReversed = Prompt-Boolean "Leader reversed?" $false

    $motors = @(
        [pscustomobject]@{
            role = "leader"
            id = $leaderId
            neutralMode = $neutral
            reversed = $leaderReversed
        }
    )

    $followerIds = Prompt-Value "Follower motor CAN IDs, comma-separated (blank for none)" ""
    foreach ($idText in ($followerIds -split "," | ForEach-Object { $_.Trim() } | Where-Object { $_.Length -gt 0 })) {
        $followerId = [int]$idText
        $motors += [pscustomobject]@{
            role = "follower"
            id = $followerId
            reversed = Prompt-Boolean "Follower $followerId reversed?" $false
        }
    }

    return $motors
}

function New-InteractivePidConfig {
    if (-not (Prompt-Boolean "Configure PID/feedforward values?" $false)) {
        return [ordered]@{
            kP = "0.0"
            kI = "0.0"
            kD = "0.0"
            kG = "0.0"
            kS = $null
            kV = $null
            kA = $null
        }
    }

    return [ordered]@{
        kP = Prompt-DoubleText "kP" "0.0"
        kI = Prompt-DoubleText "kI" "0.0"
        kD = Prompt-DoubleText "kD" "0.0"
        kG = Prompt-DoubleText "kG" "0.0"
        kS = Prompt-OptionalDoubleText "kS"
        kV = Prompt-OptionalDoubleText "kV"
        kA = Prompt-OptionalDoubleText "kA"
    }
}

function New-InteractiveSubsystem {
    $rawName = Prompt-Required "Subsystem name, example shooter"
    $type = (Prompt-Enum "Subsystem type" @("velocity", "position") "velocity").ToLowerInvariant()
    $stableId = Convert-ToCamelCase (Convert-ToPascalCase $rawName)

    $subsystem = [ordered]@{
        id = $stableId
        name = $rawName
        type = $type
        motors = @(New-InteractiveMotors)
        pid = New-InteractivePidConfig
        ratios = [ordered]@{
            sensorToMechanism = Prompt-DoubleText "Sensor-to-mechanism ratio" "1.0"
            rotorToSensor = Prompt-DoubleText "Rotor-to-sensor ratio" "1.0"
        }
        motionMagic = [ordered]@{}
    }

    if ($type -eq "position") {
        $subsystem.cancoder = [ordered]@{
            id = Prompt-Int "CANcoder CAN ID"
            magnetOffset = Prompt-DoubleText "CANcoder magnet offset rotations" "0.0"
            discontinuityPoint = Prompt-DoubleText "CANcoder discontinuity point rotations" "0.5"
        }
        $subsystem.motionMagic.cruiseVelocity = Prompt-DoubleText "Motion Magic cruise velocity" "0.0"
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
        $subsystem.position = [ordered]@{
            units = Prompt-Value "Position units" "rotations"
            default = Prompt-OptionalDoubleText "Default position"
        }
    } else {
        $subsystem.motionMagic.acceleration = Prompt-DoubleText "Motion Magic acceleration" "0.0"
    }

    return [pscustomobject]$subsystem
}

function Read-SubsystemDocument {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return [pscustomobject]@{ subsystems = @() }
    }

    $document = Get-Content -Path $Path -Raw | ConvertFrom-Json
    if (-not ($document.PSObject.Properties.Name -contains "subsystems")) {
        $document | Add-Member -MemberType NoteProperty -Name subsystems -Value @()
    }

    $document.subsystems = @($document.subsystems)
    foreach ($subsystem in @($document.subsystems)) {
        if (-not ($subsystem.PSObject.Properties.Name -contains "id") -or [string]::IsNullOrWhiteSpace($subsystem.id)) {
            $subsystem | Add-Member -MemberType NoteProperty -Name id -Value (Get-StableSubsystemId $subsystem) -Force
        }
    }
    return $document
}

function Save-SubsystemDocument {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)]$Document
    )

    $Document.subsystems = @($Document.subsystems | Sort-Object { (Get-SubsystemMetadata $_).PascalName })
    $Document | ConvertTo-Json -Depth 12 | Set-Content -Path $Path -Encoding ascii
}

function Upsert-SubsystemDocumentEntry {
    param(
        [Parameter(Mandatory = $true)]$Document,
        [Parameter(Mandatory = $true)]$Subsystem
    )

    $metadata = Get-SubsystemMetadata $Subsystem
    $Document.subsystems = @($Document.subsystems | Where-Object { (Get-SubsystemMetadata $_).Id -ne $metadata.Id })
    $Document.subsystems += $Subsystem
}

function New-VelocityConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorList = Format-IndentedList (Convert-MotorsToExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.VelocitySubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
  public static final VelocitySubsystemConfig $($Metadata.ConfigConstantName) =
      new VelocitySubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              $($Subsystem.pid.kP),
              $($Subsystem.pid.kI),
              $($Subsystem.pid.kD),
              $($Subsystem.pid.kG),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kS),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kV),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kA),
              $($Subsystem.ratios.sensorToMechanism),
              $($Subsystem.ratios.rotorToSensor)),
          MotionMagicConfig.forVelocity($($Subsystem.motionMagic.acceleration)),
          "$($Metadata.PascalName)");

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function New-PositionConstantsContent {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata
    )

    $motorList = Format-IndentedList (Convert-MotorsToExpressions $Subsystem) "              "

    return @"
package frc.robot.constants;

$GeneratedFileMarker
$SubsystemIdMarkerPrefix$($Metadata.Id)

import com.ctre.phoenix6.signals.NeutralModeValue;
import frc.powerlib.configs.CancoderConfig;
import frc.powerlib.configs.LeadMotorConfig;
import frc.powerlib.configs.MotionMagicConfig;
import frc.powerlib.configs.MotorConfig;
import frc.powerlib.configs.PositionSubsystemConfig;
import java.util.List;
import java.util.Optional;

public class $($Metadata.PascalName)Constants {
  public static final PositionSubsystemConfig $($Metadata.ConfigConstantName) =
      new PositionSubsystemConfig(
          List.of(
$motorList),
          new LeadMotorConfig(
              $($Subsystem.pid.kP),
              $($Subsystem.pid.kI),
              $($Subsystem.pid.kD),
              $($Subsystem.pid.kG),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kS),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kV),
              $(Get-OptionalDoubleExpression $Subsystem.pid.kA),
              $($Subsystem.ratios.sensorToMechanism),
              $($Subsystem.ratios.rotorToSensor)),
          new CancoderConfig($($Subsystem.cancoder.id), $($Subsystem.cancoder.magnetOffset), $($Subsystem.cancoder.discontinuityPoint)),
          new MotionMagicConfig($($Subsystem.motionMagic.cruiseVelocity), $($Subsystem.motionMagic.acceleration)),
          "$($Metadata.PascalName)",
          "$($Subsystem.position.units)",
          $(Get-OptionalDoubleExpression $Subsystem.position.default));

$CustomConstantsStartMarker
$CustomConstantsEndMarker
}
"@
}

function Ensure-ConstantsMarkers {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $content = Get-Content -Path $ConstantsPath -Raw
    if ($content.Contains($ConstantsStartMarker) -and $content.Contains($ConstantsEndMarker)) {
        return
    }

    $index = $content.LastIndexOf("}")
    if ($index -lt 0) {
        throw "Could not find closing brace in Constants.java."
    }

    $markers = "$ConstantsStartMarker`n$ConstantsEndMarker`n"
    $updated = $content.Substring(0, $index).TrimEnd() + "`n`n$markers}"
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Remove-UnmarkedGeneratedConstants {
    param([Parameter(Mandatory = $true)][string]$ConstantsPath)

    $lines = @(Get-Content -Path $ConstantsPath)
    $kept = @()
    foreach ($line in $lines) {
        $match = [regex]::Match($line, "^\s*public static final class\s+([A-Za-z0-9_]+)\s+extends\s+frc\.robot\.constants\.[A-Za-z0-9_]+Constants\s+\{\}\s*$")
        if ($match.Success -and -not ($BuiltInConstantNames -contains $match.Groups[1].Value)) {
            continue
        }
        $kept += $line
    }

    Set-Content -Path $ConstantsPath -Value ($kept -join "`n") -Encoding ascii
}

function Rewrite-ConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$ConstantsPath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    Ensure-ConstantsMarkers $ConstantsPath
    Remove-UnmarkedGeneratedConstants $ConstantsPath
    Ensure-ConstantsMarkers $ConstantsPath

    $content = Get-Content -Path $ConstantsPath -Raw
    $start = $content.IndexOf($ConstantsStartMarker) + $ConstantsStartMarker.Length
    $end = $content.IndexOf($ConstantsEndMarker)
    $entries = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $entries += "  public static final class $($metadata.PascalName) extends frc.robot.constants.$($metadata.PascalName)Constants {}"
    }

    $block = if ($entries.Count -eq 0) { "" } else { "`n" + ($entries -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $ConstantsPath -Value $updated -Encoding ascii
}

function Rewrite-StateMachineBlock {
    param(
        [Parameter(Mandatory = $true)][string]$StateMachinePath,
        [Parameter(Mandatory = $true)]$Subsystems
    )

    $content = Get-Content -Path $StateMachinePath -Raw
    if (-not $content.Contains($StateMachineStartMarker) -or -not $content.Contains($StateMachineEndMarker)) {
        throw "Could not find POWERLIB GENERATED SUBSYSTEMS markers in StateMachine.java. Re-run the installer or add the DO NOT DELETE markers manually."
    }

    $fields = @()
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $fields += "  public final $($metadata.SubsystemClassName) $($metadata.CamelName) = new $($metadata.SubsystemClassName)(Constants.$($metadata.PascalName).$($metadata.ConfigConstantName));"
    }

    $start = $content.IndexOf($StateMachineStartMarker) + $StateMachineStartMarker.Length
    $end = $content.IndexOf($StateMachineEndMarker)
    $block = if ($fields.Count -eq 0) { "`n" } else { "`n" + ($fields -join "`n") + "`n" }
    $updated = $content.Substring(0, $start) + $block + $content.Substring($end)
    Set-Content -Path $StateMachinePath -Value $updated -Encoding ascii
}

function Get-PreservedCustomConstantsBlock {
    param([Parameter(Mandatory = $true)][string]$Path)

    if (-not (Test-Path $Path)) {
        return $null
    }

    $content = Get-Content -Path $Path -Raw
    if (-not $content.Contains($CustomConstantsStartMarker) -or -not $content.Contains($CustomConstantsEndMarker)) {
        return $null
    }

    $start = $content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $content.IndexOf($CustomConstantsEndMarker)
    return $content.Substring($start, $end - $start).Trim("`r", "`n")
}

function Get-SubsystemIdFromGeneratedContent {
    param([Parameter(Mandatory = $true)][string]$Content)

    foreach ($line in ($Content -split "`r?`n")) {
        if ($line.StartsWith($SubsystemIdMarkerPrefix)) {
            return $line.Substring($SubsystemIdMarkerPrefix.Length).Trim()
        }
    }

    return $null
}

function Get-CustomConstantsBySubsystemId {
    param([Parameter(Mandatory = $true)][string]$ConstantsDir)

    $customBlocks = @{}
    if (-not (Test-Path $ConstantsDir)) {
        return $customBlocks
    }

    Get-ChildItem -Path $ConstantsDir -Filter "*Constants.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw
        if (-not $content.Contains($GeneratedFileMarker)) {
            return
        }

        $id = Get-SubsystemIdFromGeneratedContent $content
        if (-not [string]::IsNullOrWhiteSpace($id)) {
            $customBlock = Get-PreservedCustomConstantsBlock $_.FullName
            if (-not [string]::IsNullOrWhiteSpace($customBlock)) {
                $customBlocks[$id] = $customBlock
            }
        }
    }

    return $customBlocks
}

function Set-CustomConstantsBlock {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [AllowNull()][string]$CustomContent
    )

    if ([string]::IsNullOrWhiteSpace($CustomContent)) {
        return $Content
    }

    $start = $Content.IndexOf($CustomConstantsStartMarker) + $CustomConstantsStartMarker.Length
    $end = $Content.IndexOf($CustomConstantsEndMarker)
    if ($start -lt $CustomConstantsStartMarker.Length -or $end -lt 0) {
        return $Content
    }

    return $Content.Substring(0, $start) + "`n" + $CustomContent.Trim("`r", "`n") + "`n" + $Content.Substring($end)
}

function Write-ConstantsFile {
    param(
        [Parameter(Mandatory = $true)]$Subsystem,
        [Parameter(Mandatory = $true)]$Metadata,
        [Parameter(Mandatory = $true)]$CustomBlocksById
    )

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    New-Item -ItemType Directory -Force -Path $constantsDir | Out-Null

    $outputFile = Join-Path $constantsDir "$($Metadata.PascalName)Constants.java"
    $customContent = if ($CustomBlocksById.ContainsKey($Metadata.Id)) {
        $CustomBlocksById[$Metadata.Id]
    } else {
        Get-PreservedCustomConstantsBlock $outputFile
    }
    $content = if ($Metadata.Type -eq "velocity") {
        New-VelocityConstantsContent $Subsystem $Metadata
    } else {
        New-PositionConstantsContent $Subsystem $Metadata
    }
    $content = Set-CustomConstantsBlock $content $customContent

    Set-Content -Path $outputFile -Value $content -Encoding ascii
    return $outputFile
}

function Remove-DeletedGeneratedFiles {
    param([Parameter(Mandatory = $true)]$Subsystems)

    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    if (-not (Test-Path $constantsDir)) {
        return
    }

    $wantedFiles = @{}
    foreach ($subsystem in @($Subsystems)) {
        $metadata = Get-SubsystemMetadata $subsystem
        $wantedFiles["$($metadata.PascalName)Constants.java"] = $true
    }

    Get-ChildItem -Path $constantsDir -Filter "*Constants.java" -File | ForEach-Object {
        $content = Get-Content -Path $_.FullName -Raw
        if ($content.Contains($GeneratedFileMarker) -and -not $wantedFiles.ContainsKey($_.Name)) {
            Remove-Item -LiteralPath $_.FullName -Force
            Write-Host "Deleted removed subsystem constants $($_.Name)"
        }
    }
}

function Update-SubsystemsFromJson {
    param([Parameter(Mandatory = $true)][string]$JsonPath)

    $document = Read-SubsystemDocument $JsonPath
    $subsystems = @($document.subsystems)

    $constantsBarrel = Join-Path (Get-Location) "src/main/java/frc/robot/Constants.java"
    if (-not (Test-Path $constantsBarrel)) {
        throw "Missing src/main/java/frc/robot/Constants.java. Run robotLibraryInstall first."
    }

    $stateMachineFile = Join-Path (Get-Location) "src/main/java/frc/robot/subsystems/StateMachine.java"
    if (-not (Test-Path $stateMachineFile)) {
        throw "Missing src/main/java/frc/robot/subsystems/StateMachine.java. Run robotLibraryInstall first."
    }

    $written = @()
    $constantsDir = Join-Path (Get-Location) "src/main/java/frc/robot/constants"
    $customBlocksById = Get-CustomConstantsBySubsystemId $constantsDir
    foreach ($subsystem in $subsystems) {
        $metadata = Get-SubsystemMetadata $subsystem
        $written += Write-ConstantsFile $subsystem $metadata $customBlocksById
    }

    Rewrite-ConstantsBlock $constantsBarrel $subsystems
    Rewrite-StateMachineBlock $stateMachineFile $subsystems
    Remove-DeletedGeneratedFiles $subsystems
    Save-SubsystemDocument $JsonPath $document

    foreach ($file in $written) {
        Write-Host "Generated $file"
    }
    Write-Host "Updated Constants.java and StateMachine.java from $JsonPath"
}

function Invoke-BuildIfNeeded {
    if ($SkipBuild) {
        return
    }

    $isWindowsHost = [System.Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT
    $gradlew = if ($isWindowsHost) { ".\gradlew.bat" } else { "./gradlew" }
    if (Test-Path $gradlew) {
        & $gradlew --no-daemon --console=plain build
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
    } else {
        Write-Host "Skipped build because no Gradle wrapper was found."
    }
}

if ($UpdateSubsystems) {
    Update-SubsystemsFromJson $SubsystemsJson
    Invoke-BuildIfNeeded
    exit 0
}

Write-Host "PowerLib subsystem generator starting. Answer the prompts below."
Write-Host "Enum prompts show accepted values before the default."

if ((Test-Path $SubsystemsJson) -and (Prompt-Boolean "Update subsystems from ${SubsystemsJson}?" $true)) {
    Update-SubsystemsFromJson $SubsystemsJson
    Invoke-BuildIfNeeded
    exit 0
}

$document = Read-SubsystemDocument $SubsystemsJson

do {
    $subsystem = New-InteractiveSubsystem
    Upsert-SubsystemDocumentEntry $document $subsystem
    Save-SubsystemDocument $SubsystemsJson $document
    Update-SubsystemsFromJson $SubsystemsJson
    $addAnother = Prompt-Boolean "Add another subsystem?" $false
} while ($addAnother)

Invoke-BuildIfNeeded
