package frc.robot;

// Generated by PowerLib subsystem tool. Edit powerlib-bindings.json, then run update.

import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.InstantCommand;
import edu.wpi.first.wpilibj2.command.button.CommandXboxController;
import frc.robot.subsystems.StateMachine;

public final class PowerButtonBindings {
  private PowerButtonBindings() {}

  public static void configure(
      CommandXboxController driverController,
      CommandXboxController operatorController,
      StateMachine stateMachine) {}
}
